=== rootmp/multiprof/dist/gameserver/data/parser/option_data/option_data.dtd
<!ELEMENT list (option_data)*>
<!ELEMENT option_data  (for|set|skills|triggers)*>
<!ATTLIST option_data
	id CDATA #REQUIRED>

<!ELEMENT for (add|p_critical_damage|p_magic_critical_dmg|p_skill_critical_damage|p_heal_effect|p_elemental_exp_rate|p_elemental_attack|p_elemental_defence|p_elemental_crit_rate|p_elemental_crit_attack|p_attack_trait|p_defence_trait|set|mul|stat_effect)*>
<!ELEMENT mul (player|target|using|zone)*>
<!ATTLIST mul
	order CDATA #REQUIRED
	stat CDATA #REQUIRED
	value CDATA #REQUIRED>

<!ELEMENT add (player|target|using|zone|or|not|and)*>
<!ATTLIST add
	order CDATA #REQUIRED
	stat CDATA #REQUIRED
	value CDATA #REQUIRED>

<!ELEMENT p_critical_damage (player|target|using|zone|has|game|or|not|and)*>
<!ATTLIST p_critical_damage
	value CDATA #REQUIRED
	type CDATA #REQUIRED>

<!ELEMENT p_magic_critical_dmg (player|target|using|zone|has|game|or|not|and)*>
<!ATTLIST p_magic_critical_dmg
	value CDATA #REQUIRED
	type CDATA #REQUIRED>

<!ELEMENT p_skill_critical_damage (player|target|using|zone|has|game|or|not|and)*>
<!ATTLIST p_skill_critical_damage
	value CDATA #REQUIRED
	type CDATA #REQUIRED>

<!ELEMENT p_heal_effect (player|target|using|zone|has|game|or|not|and)*>
<!ATTLIST p_heal_effect
	value CDATA #REQUIRED
	type CDATA #REQUIRED>
	
<!ELEMENT stat_effect (player|target|using|zone|has|game|or|not|and)*>
<!ATTLIST stat_effect
	name CDATA #REQUIRED
	value CDATA #REQUIRED
	type CDATA #REQUIRED>

<!ELEMENT p_elemental_exp_rate (player|target|using|zone|has|game|or|not|and)*>
<!ATTLIST p_elemental_exp_rate
	element CDATA #REQUIRED
	value CDATA #REQUIRED>

<!ELEMENT p_elemental_attack (player|target|using|zone|has|game|or|not|and)*>
<!ATTLIST p_elemental_attack
	element CDATA #REQUIRED
	value CDATA #REQUIRED
	type CDATA #REQUIRED>

<!ELEMENT p_elemental_defence (player|target|using|zone|has|game|or|not|and)*>
<!ATTLIST p_elemental_defence
	element CDATA #REQUIRED
	value CDATA #REQUIRED
	type CDATA #REQUIRED>

<!ELEMENT p_elemental_crit_rate (player|target|using|zone|has|game|or|not|and)*>
<!ATTLIST p_elemental_crit_rate
	element CDATA #REQUIRED
	value CDATA #REQUIRED
	type CDATA #REQUIRED>

<!ELEMENT p_elemental_crit_attack (player|target|using|zone|has|game|or|not|and)*>
<!ATTLIST p_elemental_crit_attack
	element CDATA #REQUIRED
	value CDATA #REQUIRED
	type CDATA #REQUIRED>

<!ELEMENT p_attack_trait (player|target|using|zone|or|not|and)*>
<!ATTLIST p_attack_trait
	name CDATA #REQUIRED
	value CDATA #REQUIRED>

<!ELEMENT p_defence_trait (player|target|using|zone|or|not|and)*>
<!ATTLIST p_defence_trait
	name CDATA #REQUIRED
	value CDATA #REQUIRED>

<!ELEMENT set (player|target|using|zone|or|not|and)*>
<!ATTLIST set
	order CDATA #IMPLIED
	stat CDATA #IMPLIED
	value CDATA #REQUIRED>


<!ELEMENT or (player|target|using|zone)*>
<!ELEMENT not (player|target|using|zone)*>
<!ELEMENT and (player|target|using|zone)*>



<!ELEMENT skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED>

<!ELEMENT triggers (trigger)*>
<!ELEMENT trigger (#PCDATA)>
<!ATTLIST trigger
	id CDATA #REQUIRED
	level CDATA #REQUIRED
	type CDATA #REQUIRED
	chance CDATA #REQUIRED>

<!ELEMENT player (#PCDATA)>
<!ATTLIST player
	residence CDATA #IMPLIED
	classId CDATA #IMPLIED>
<!ELEMENT target (#PCDATA)>
<!ATTLIST target
	pvp CDATA #REQUIRED>
<!ELEMENT using (#PCDATA)>
<!ATTLIST using
	slotitem CDATA #REQUIRED>
<!ELEMENT zone (#PCDATA)>
<!ATTLIST zone
	type CDATA #REQUIRED>

=== rootmp/multiprof/dist/gameserver/data/parser/option_data/30100-30199.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "option_data.dtd">
<list>
	<option_data id="30176">
		<for>
		</for>
	</option_data>
	<option_data id="30177">
		<for>
			<add order="0x60" stat="mDef" value="1"/>
			<!--Маг. Защ. +1-->
		</for>
	</option_data>
	<option_data id="30178">
		<for>
			<add order="0x60" stat="mDef" value="2"/>
			<!--Маг. Защ. +2-->
		</for>
	</option_data>
	<option_data id="30179">
		<for>
			<add order="0x60" stat="mDef" value="3"/>
			<!--Маг. Защ. +3-->
		</for>
	</option_data>
	<option_data id="30180">
		<for>
			<add order="0x60" stat="mDef" value="4"/>
			<!--Маг. Защ. +4-->
		</for>
	</option_data>
	<option_data id="30181">
		<for>
			<add order="0x60" stat="mDef" value="5"/>
			<!--Маг. Защ. +5-->
		</for>
	</option_data>
	<option_data id="30182">
		<for>
			<add order="0x60" stat="mDef" value="6"/>
			<!--Маг. Защ. +6-->
		</for>
	</option_data>
	<option_data id="30183">
		<for>
			<add order="0x60" stat="mDef" value="7"/>
			<!--Маг. Защ. +7-->
		</for>
	</option_data>
	<option_data id="30184">
		<for>
			<add order="0x60" stat="mDef" value="8"/>
			<!--Маг. Защ. +8-->
		</for>
	</option_data>
	<option_data id="30185">
		<for>
			<add order="0x60" stat="mDef" value="9"/>
			<!--Маг. Защ. +9-->
		</for>
	</option_data>
	<option_data id="30186">
		<for>
			<add order="0x60" stat="mDef" value="10"/>
			<!--Маг. Защ. +10-->
		</for>
	</option_data>
	<option_data id="30187">
		<for>
			<add order="0x60" stat="mDef" value="11"/>
			<!--Маг. Защ. +11-->
		</for>
	</option_data>
	<option_data id="30188">
		<for>
			<add order="0x60" stat="mDef" value="12"/>
			<!--Маг. Защ. +12-->
		</for>
	</option_data>
	<option_data id="30189">
		<for>
			<add order="0x60" stat="mDef" value="13"/>
			<!--Маг. Защ. +13-->
		</for>
	</option_data>
	<option_data id="30190">
		<for>
			<add order="0x60" stat="mDef" value="14"/>
			<!--Маг. Защ. +14-->
		</for>
	</option_data>
	<option_data id="30191">
		<for>
			<add order="0x60" stat="mDef" value="15"/>
			<!--Маг. Защ. +15-->
		</for>
	</option_data>
	<option_data id="30192">
		<for>
			<add order="0x60" stat="mDef" value="16"/>
			<!--Маг. Защ. +16-->
		</for>
	</option_data>
	<option_data id="30193">
		<for>
			<add order="0x60" stat="mDef" value="17"/>
			<!--Маг. Защ. +17-->
		</for>
	</option_data>
	<option_data id="30194">
		<for>
			<add order="0x60" stat="mDef" value="18"/>
			<!--Маг. Защ. +18-->
		</for>
	</option_data>
	<option_data id="30195">
		<for>
			<add order="0x60" stat="mDef" value="19"/>
			<!--Маг. Защ. +19-->
		</for>
	</option_data>
	<option_data id="30196">
		<for>
			<add order="0x60" stat="mDef" value="20"/>
			<!--Маг. Защ. +20-->
		</for>
	</option_data>
	<option_data id="30197">
		<for>
			<add order="0x60" stat="mDef" value="21"/>
			<!--Маг. Защ. +21-->
		</for>
	</option_data>
	<option_data id="30198">
		<for>
			<add order="0x60" stat="mDef" value="22"/>
			<!--Маг. Защ. +22-->
		</for>
	</option_data>
	<option_data id="30199">
		<for>
			<add order="0x60" stat="mDef" value="23"/>
			<!--Маг. Защ. +23-->
		</for>
	</option_data>
</list>

=== rootmp/multiprof/dist/gameserver/data/parser/option_data/36600-36699.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "option_data.dtd">
<list>
	<option_data id="36600">
		<!--P. Evasion +1.7-->
	</option_data>
	<option_data id="36601">
		<!--P. Evasion +1.8-->
	</option_data>
	<option_data id="36602">
		<!--P. Evasion +2.0-->
	</option_data>
	<option_data id="36603">
		<!--P. Evasion +3.0-->
	</option_data>
	<option_data id="36604">
		<!--M. Evasion +1.0-->
	</option_data>
	<option_data id="36605">
		<!--M. Evasion +1.0-->
	</option_data>
	<option_data id="36606">
		<!--M. Evasion +1.0-->
	</option_data>
	<option_data id="36607">
		<!--M. Evasion +1.0-->
	</option_data>
	<option_data id="36608">
		<!--M. Evasion +1.0-->
	</option_data>
	<option_data id="36609">
		<!--M. Evasion +1.0-->
	</option_data>
	<option_data id="36610">
		<!--M. Evasion +1.0-->
	</option_data>
	<option_data id="36611">
		<!--M. Evasion +1.1-->
	</option_data>
	<option_data id="36612">
		<!--M. Evasion +1.1-->
	</option_data>
	<option_data id="36613">
		<!--M. Evasion +1.2-->
	</option_data>
	<option_data id="36614">
		<!--M. Evasion +1.2-->
	</option_data>
	<option_data id="36615">
		<!--M. Evasion +1.2-->
	</option_data>
	<option_data id="36616">
		<!--M. Evasion +1.2-->
	</option_data>
	<option_data id="36617">
		<!--M. Evasion +1.3-->
	</option_data>
	<option_data id="36618">
		<!--M. Evasion +1.4-->
	</option_data>
	<option_data id="36619">
		<!--M. Evasion +1.5-->
	</option_data>
	<option_data id="36620">
		<!--M. Evasion +1.7-->
	</option_data>
	<option_data id="36621">
		<!--M. Evasion +1.8-->
	</option_data>
	<option_data id="36622">
		<!--M. Evasion +2.0-->
	</option_data>
	<option_data id="36623">
		<!--M. Evasion +3.0-->
	</option_data>
	<option_data id="36624">
		<!--M. Evasion +1.0-->
	</option_data>
	<option_data id="36625">
		<!--M. Evasion +1.0-->
	</option_data>
	<option_data id="36626">
		<!--M. Evasion +1.0-->
	</option_data>
	<option_data id="36627">
		<!--M. Evasion +1.0-->
	</option_data>
	<option_data id="36628">
		<!--M. Evasion +1.0-->
	</option_data>
	<option_data id="36629">
		<!--M. Evasion +1.0-->
	</option_data>
	<option_data id="36630">
		<!--M. Evasion +1.0-->
	</option_data>
	<option_data id="36631">
		<!--M. Evasion +1.1-->
	</option_data>
	<option_data id="36632">
		<!--M. Evasion +1.1-->
	</option_data>
	<option_data id="36633">
		<!--M. Evasion +1.2-->
	</option_data>
	<option_data id="36634">
		<!--M. Evasion +1.2-->
	</option_data>
	<option_data id="36635">
		<!--M. Evasion +1.2-->
	</option_data>
	<option_data id="36636">
		<!--M. Evasion +1.2-->
	</option_data>
	<option_data id="36637">
		<!--M. Evasion +1.3-->
	</option_data>
	<option_data id="36638">
		<!--M. Evasion +1.4-->
	</option_data>
	<option_data id="36639">
		<!--M. Evasion +1.5-->
	</option_data>
	<option_data id="36640">
		<!--M. Evasion +1.7-->
	</option_data>
	<option_data id="36641">
		<!--M. Evasion +1.8-->
	</option_data>
	<option_data id="36642">
		<!--M. Evasion +2.0-->
	</option_data>
	<option_data id="36643">
		<!--M. Evasion +3.0-->
	</option_data>
	<option_data id="36644">
		<!--M. Evasion +1.0-->
	</option_data>
	<option_data id="36645">
		<!--M. Evasion +1.0-->
	</option_data>
	<option_data id="36646">
		<!--M. Evasion +1.0-->
	</option_data>
	<option_data id="36647">
		<!--M. Evasion +1.0-->
	</option_data>
	<option_data id="36648">
		<!--M. Evasion +1.0-->
	</option_data>
	<option_data id="36649">
		<!--M. Evasion +1.0-->
	</option_data>
	<option_data id="36650">
		<!--M. Evasion +1.0-->
	</option_data>
	<option_data id="36651">
		<!--M. Evasion +1.1-->
	</option_data>
	<option_data id="36652">
		<!--M. Evasion +1.1-->
	</option_data>
	<option_data id="36653">
		<!--M. Evasion +1.2-->
	</option_data>
	<option_data id="36654">
		<!--M. Evasion +1.2-->
	</option_data>
	<option_data id="36655">
		<!--M. Evasion +1.2-->
	</option_data>
	<option_data id="36656">
		<!--M. Evasion +1.2-->
	</option_data>
	<option_data id="36657">
		<!--M. Evasion +1.3-->
	</option_data>
	<option_data id="36658">
		<!--M. Evasion +1.4-->
	</option_data>
	<option_data id="36659">
		<!--M. Evasion +1.5-->
	</option_data>
	<option_data id="36660">
		<!--M. Evasion +1.7-->
	</option_data>
	<option_data id="36661">
		<!--M. Evasion +1.8-->
	</option_data>
	<option_data id="36662">
		<!--M. Evasion +2.0-->
	</option_data>
	<option_data id="36663">
		<!--M. Evasion +3.0-->
	</option_data>
	<option_data id="36664">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36665">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36666">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36667">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36668">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36669">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36670">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36671">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36672">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36673">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36674">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36675">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36676">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36677">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36678">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36679">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36680">
		<!--Received damage -2%-->
	</option_data>
	<option_data id="36681">
		<!--Received damage -2%-->
	</option_data>
	<option_data id="36682">
		<!--Received damage -2%-->
	</option_data>
	<option_data id="36683">
		<!--Received damage -3%-->
	</option_data>
	<option_data id="36684">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36685">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36686">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36687">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36688">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36689">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36690">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36691">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36692">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36693">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36694">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36695">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36696">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36697">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36698">
		<!--Received damage -1%-->
	</option_data>
	<option_data id="36699">
		<!--Received damage -1%-->
	</option_data>
</list>

=== rootmp/multiprof/dist/gameserver/data/parser/option_data/16100-16199.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "option_data.dtd">
<list>
	<option_data id="16163">
		<skills>
			<skill id="3203" level="1"/> <!--Item Skill: Mystery Skill-->
		</skills>
	</option_data>
	<option_data id="16164">
		<skills>
			<skill id="3143" level="10"/> <!--Item Skill: Kiss of Eva-->
		</skills>
	</option_data>
	<option_data id="16165">
		<skills>
			<skill id="3144" level="10"/> <!--Item Skill: Acrobatics-->
		</skills>
	</option_data>
	<option_data id="16166">
		<skills>
			<skill id="3145" level="10"/> <!--Item Skill: Iron Body-->
		</skills>
	</option_data>
	<option_data id="16167">
		<skills>
			<skill id="3156" level="1"/> <!--Item Skill: Firework-->
		</skills>
	</option_data>
	<option_data id="16168">
		<skills>
			<skill id="3206" level="1"/> <!--Item Skill: Music-->
		</skills>
	</option_data>
	<option_data id="16169">
		<skills>
			<skill id="3157" level="1"/> <!--Item Skill: Large Firework-->
		</skills>
	</option_data>
	<option_data id="16170">
		<triggers>
			<trigger id="3081" level="10" type="ATTACK" chance="1.0"/> <!--Item Skill: Charm-->
		</triggers>
	</option_data>
	<option_data id="16171">
		<triggers>
			<trigger id="3080" level="10" type="ATTACK" chance="1.0"/> <!--Item Skill: Aggression-->
		</triggers>
	</option_data>
	<option_data id="16172">
		<triggers>
			<trigger id="3083" level="10" type="ATTACK" chance="1.0"/> <!--Item Skill: Slow-->
		</triggers>
	</option_data>
	<option_data id="16173">
		<triggers>
			<trigger id="3109" level="10" type="CRIT" chance="5.0"/> <!--Item Skill: Aggression Down-->
		</triggers>
	</option_data>
	<option_data id="16174">
		<triggers>
			<trigger id="3108" level="10" type="CRIT" chance="5.0"/> <!--Item Skill: Aggression Up-->
		</triggers>
	</option_data>
	<option_data id="16175">
		<triggers>
			<trigger id="3111" level="10" type="CRIT" chance="5.0"/> <!--Item Skill: Slow-->
		</triggers>
	</option_data>
	<option_data id="16176">
		<triggers>
			<trigger id="3096" level="10" type="OFFENSIVE_MAGICAL_SKILL_USE" chance="2.0"/> <!--Item Skill: Slow-->
		</triggers>
	</option_data>
	<option_data id="16177">
		<skills>
			<skill id="3252" level="10"/> <!--Item Skill: Kiss of Eva-->
		</skills>
	</option_data>
	<option_data id="16178">
		<skills>
			<skill id="3253" level="10"/> <!--Item Skill: Acrobatics-->
		</skills>
	</option_data>
	<option_data id="16179">
		<skills>
			<skill id="3254" level="10"/> <!--Item Skill: Iron Body-->
		</skills>
	</option_data>
	<option_data id="16180">
		<skills>
			<skill id="3188" level="10"/> <!--Item Skill: Winter-->
		</skills>
	</option_data>
	<option_data id="16181">
		<skills>
			<skill id="3139" level="10"/> <!--Item Skill: Agility-->
		</skills>
	</option_data>
	<option_data id="16182">
		<skills>
			<skill id="3196" level="10"/> <!--Item Skill: Bleed-->
		</skills>
	</option_data>
	<option_data id="16183">
		<skills>
			<skill id="3130" level="10"/> <!--Item Skill: Ritual-->
		</skills>
	</option_data>
	<option_data id="16184">
		<skills>
			<skill id="3169" level="10"/> <!--Item Skill: Stone-->
		</skills>
	</option_data>
	<option_data id="16185">
		<skills>
			<skill id="3194" level="10"/> <!--Item Skill: Fear-->
		</skills>
	</option_data>
	<option_data id="16186">
		<skills>
			<skill id="3165" level="10"/> <!--Item Skill: Prominence-->
		</skills>
	</option_data>
	<option_data id="16187">
		<skills>
			<skill id="3151" level="10"/> <!--Item Skill: Peace-->
		</skills>
	</option_data>
	<option_data id="16188">
		<skills>
			<skill id="3150" level="10"/> <!--Item Skill: Charm-->
		</skills>
	</option_data>
	<option_data id="16189">
		<skills>
			<skill id="3149" level="10"/> <!--Item Skill: Aggression-->
		</skills>
	</option_data>
	<option_data id="16190">
		<skills>
			<skill id="3140" level="10"/> <!--Item Skill: Guidance-->
		</skills>
	</option_data>
	<option_data id="16191">
		<skills>
			<skill id="3190" level="10"/> <!--Item Skill: Hold-->
		</skills>
	</option_data>
	<option_data id="16192">
		<skills>
			<skill id="3170" level="10"/> <!--Item Skill: Solar Flare-->
		</skills>
	</option_data>
	<option_data id="16193">
		<skills>
			<skill id="3138" level="10"/> <!--Item Skill: Heal Empower-->
		</skills>
	</option_data>
	<option_data id="16194">
		<skills>
			<skill id="3126" level="10"/> <!--Item Skill: Prayer-->
		</skills>
	</option_data>
	<option_data id="16195">
		<skills>
			<skill id="3123" level="10"/> <!--Item Skill: Heal-->
		</skills>
	</option_data>
	<option_data id="16196">
		<skills>
			<skill id="3133" level="10"/> <!--Item Skill: Empower-->
		</skills>
	</option_data>
	<option_data id="16197">
		<skills>
			<skill id="3131" level="10"/> <!--Item Skill: Cheer-->
		</skills>
	</option_data>
	<option_data id="16198">
		<skills>
			<skill id="3125" level="10"/> <!--Item Skill: Battle Roar-->
		</skills>
	</option_data>
	<option_data id="16199">
		<skills>
			<skill id="3124" level="10"/> <!--Item Skill: Blessed Body-->
		</skills>
	</option_data>
</list>

=== rootmp/multiprof/dist/gameserver/data/parser/option_data/23200-23299.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "option_data.dtd">
<list>
	<option_data id="23247">
		<for>
			<add order="0x60" stat="pDef" value="41.835"/>
		</for>
	</option_data>
	<option_data id="23248">
		<for>
			<add order="0x60" stat="mDef" value="35.478"/>
		</for>
	</option_data>
	<option_data id="23249">
		<for>
			<add order="0x60" stat="maxHp" value="154.019"/>
		</for>
	</option_data>
	<option_data id="23250">
		<for>
			<add order="0x60" stat="maxMp" value="50.572"/>
		</for>
	</option_data>
	<option_data id="23251">
		<for>
			<add order="0x60" stat="maxCp" value="277.234"/>
		</for>
	</option_data>
	<option_data id="23252">
		<for>
			<add order="0x60" stat="pAtk" value="28.526"/>
		</for>
	</option_data>
	<option_data id="23253">
		<for>
			<add order="0x60" stat="mAtk" value="35.875"/>
		</for>
	</option_data>
	<option_data id="23254">
		<for>
			<add order="0x60" stat="regHp" value="0.672"/>
		</for>
	</option_data>
	<option_data id="23255">
		<for>
			<add order="0x60" stat="regMp" value="0.283"/>
		</for>
	</option_data>
	<option_data id="23256">
		<for>
			<add order="0x60" stat="regCp" value="0.672"/>
		</for>
	</option_data>
	<option_data id="23257">
		<for>
			<add order="0x60" stat="pEvasRate" value="3.389"/>
		</for>
	</option_data>
	<option_data id="23258">
		<for>
			<add order="0x60" stat="pAccCombat" value="3.389"/>
		</for>
	</option_data>
	<option_data id="23259">
		<for>
			<add order="0x60" stat="basePCritRate" value="25.52"/>
		</for>
	</option_data>
	<option_data id="23260">
		<for>
			<add order="0x60" stat="pDef" value="21.639"/>
			<add order="0x60" stat="mDef" value="17.127"/>
		</for>
	</option_data>
	<option_data id="23261">
		<for>
			<add order="0x60" stat="pDef" value="21.639"/>
			<add order="0x60" stat="maxHp" value="74.354"/>
		</for>
	</option_data>
	<option_data id="23262">
		<for>
			<add order="0x60" stat="pDef" value="21.639"/>
			<add order="0x60" stat="maxMp" value="24.414"/>
		</for>
	</option_data>
	<option_data id="23263">
		<for>
			<add order="0x60" stat="pDef" value="21.639"/>
			<add order="0x60" stat="maxCp" value="133.837"/>
		</for>
	</option_data>
	<option_data id="23264">
		<for>
			<add order="0x60" stat="pDef" value="21.639"/>
			<add order="0x60" stat="pAtk" value="13.771"/>
		</for>
	</option_data>
	<option_data id="23265">
		<for>
			<add order="0x60" stat="pDef" value="21.639"/>
			<add order="0x60" stat="mAtk" value="17.319"/>
		</for>
	</option_data>
	<option_data id="23266">
		<for>
			<add order="0x60" stat="pDef" value="21.639"/>
			<add order="0x60" stat="regHp" value="0.324"/>
		</for>
	</option_data>
	<option_data id="23267">
		<for>
			<add order="0x60" stat="pDef" value="21.639"/>
			<add order="0x60" stat="regMp" value="0.137"/>
		</for>
	</option_data>
	<option_data id="23268">
		<for>
			<add order="0x60" stat="pDef" value="21.639"/>
			<add order="0x60" stat="regCp" value="0.324"/>
		</for>
	</option_data>
	<option_data id="23269">
		<for>
			<add order="0x60" stat="pDef" value="21.639"/>
			<add order="0x60" stat="pEvasRate" value="1.636"/>
		</for>
	</option_data>
	<option_data id="23270">
		<for>
			<add order="0x60" stat="pDef" value="21.639"/>
			<add order="0x60" stat="pAccCombat" value="1.636"/>
		</for>
	</option_data>
	<option_data id="23271">
		<for>
			<add order="0x60" stat="pDef" value="21.639"/>
			<add order="0x60" stat="basePCritRate" value="12.32"/>
		</for>
	</option_data>
	<option_data id="23272">
		<for>
			<add order="0x60" stat="mDef" value="18.351"/>
			<add order="0x60" stat="maxHp" value="74.354"/>
		</for>
	</option_data>
	<option_data id="23273">
		<for>
			<add order="0x60" stat="mDef" value="18.351"/>
			<add order="0x60" stat="maxMp" value="24.414"/>
		</for>
	</option_data>
	<option_data id="23274">
		<for>
			<add order="0x60" stat="mDef" value="18.351"/>
			<add order="0x60" stat="maxCp" value="133.837"/>
		</for>
	</option_data>
	<option_data id="23275">
		<for>
			<add order="0x60" stat="mDef" value="18.351"/>
			<add order="0x60" stat="pAtk" value="13.771"/>
		</for>
	</option_data>
	<option_data id="23276">
		<for>
			<add order="0x60" stat="mDef" value="18.351"/>
			<add order="0x60" stat="mAtk" value="17.319"/>
		</for>
	</option_data>
	<option_data id="23277">
		<for>
			<add order="0x60" stat="mDef" value="18.351"/>
			<add order="0x60" stat="regHp" value="0.324"/>
		</for>
	</option_data>
	<option_data id="23278">
		<for>
			<add order="0x60" stat="mDef" value="18.351"/>
			<add order="0x60" stat="regMp" value="0.137"/>
		</for>
	</option_data>
	<option_data id="23279">
		<for>
			<add order="0x60" stat="mDef" value="18.351"/>
			<add order="0x60" stat="regCp" value="0.324"/>
		</for>
	</option_data>
	<option_data id="23280">
		<for>
			<add order="0x60" stat="mDef" value="18.351"/>
			<add order="0x60" stat="pEvasRate" value="1.636"/>
		</for>
	</option_data>
	<option_data id="23281">
		<for>
			<add order="0x60" stat="mDef" value="18.351"/>
			<add order="0x60" stat="pAccCombat" value="1.636"/>
		</for>
	</option_data>
	<option_data id="23282">
		<for>
			<add order="0x60" stat="mDef" value="18.351"/>
			<add order="0x60" stat="basePCritRate" value="12.32"/>
		</for>
	</option_data>
	<option_data id="23283">
		<for>
			<add order="0x60" stat="maxHp" value="79.665"/>
			<add order="0x60" stat="maxMp" value="24.414"/>
		</for>
	</option_data>
	<option_data id="23284">
		<for>
			<add order="0x60" stat="maxHp" value="79.665"/>
			<add order="0x60" stat="maxCp" value="133.837"/>
		</for>
	</option_data>
	<option_data id="23285">
		<for>
			<add order="0x60" stat="maxHp" value="79.665"/>
			<add order="0x60" stat="pAtk" value="13.771"/>
		</for>
	</option_data>
	<option_data id="23286">
		<for>
			<add order="0x60" stat="maxHp" value="79.665"/>
			<add order="0x60" stat="mAtk" value="17.319"/>
		</for>
	</option_data>
	<option_data id="23287">
		<for>
			<add order="0x60" stat="maxHp" value="79.665"/>
			<add order="0x60" stat="regHp" value="0.324"/>
		</for>
	</option_data>
	<option_data id="23288">
		<for>
			<add order="0x60" stat="maxHp" value="79.665"/>
			<add order="0x60" stat="regMp" value="0.137"/>
		</for>
	</option_data>
	<option_data id="23289">
		<for>
			<add order="0x60" stat="maxHp" value="79.665"/>
			<add order="0x60" stat="regCp" value="0.324"/>
		</for>
	</option_data>
	<option_data id="23290">
		<for>
			<add order="0x60" stat="maxHp" value="79.665"/>
			<add order="0x60" stat="pEvasRate" value="1.636"/>
		</for>
	</option_data>
	<option_data id="23291">
		<for>
			<add order="0x60" stat="maxHp" value="79.665"/>
			<add order="0x60" stat="pAccCombat" value="1.636"/>
		</for>
	</option_data>
	<option_data id="23292">
		<for>
			<add order="0x60" stat="maxHp" value="79.665"/>
			<add order="0x60" stat="basePCritRate" value="12.32"/>
		</for>
	</option_data>
	<option_data id="23293">
		<for>
			<add order="0x60" stat="maxMp" value="26.158"/>
			<add order="0x60" stat="maxCp" value="133.837"/>
		</for>
	</option_data>
	<option_data id="23294">
		<for>
			<add order="0x60" stat="maxMp" value="26.158"/>
			<add order="0x60" stat="pAtk" value="13.771"/>
		</for>
	</option_data>
	<option_data id="23295">
		<for>
			<add order="0x60" stat="maxMp" value="26.158"/>
			<add order="0x60" stat="mAtk" value="17.319"/>
		</for>
	</option_data>
	<option_data id="23296">
		<for>
			<add order="0x60" stat="maxMp" value="26.158"/>
			<add order="0x60" stat="regHp" value="0.324"/>
		</for>
	</option_data>
	<option_data id="23297">
		<for>
			<add order="0x60" stat="maxMp" value="26.158"/>
			<add order="0x60" stat="regMp" value="0.137"/>
		</for>
	</option_data>
	<option_data id="23298">
		<for>
			<add order="0x60" stat="maxMp" value="26.158"/>
			<add order="0x60" stat="regCp" value="0.324"/>
		</for>
	</option_data>
	<option_data id="23299">
		<for>
			<add order="0x60" stat="maxMp" value="26.158"/>
			<add order="0x60" stat="pEvasRate" value="1.636"/>
		</for>
	</option_data>
</list>
