=== rootmp/multiprof/dist/gameserver/data/parser/items/item.dtd
<!ELEMENT list (weapon|etcitem|armor)*>
<!ELEMENT weapon  (set|equip|for|cond|skills|triggers|attributes|enchant_options)*>
<!ATTLIST weapon
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	add_name CDATA #IMPLIED>
<!ELEMENT etcitem (set|equip|for|cond|skills|triggers|enchant_options|capsuled_items|create_items|create_item_groups)*>
<!ATTLIST etcitem
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	add_name CDATA #IMPLIED>
<!ELEMENT armor  (set|equip|for|cond|skills|triggers|attributes|enchant_options|agathion_data)*>
<!ATTLIST armor
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	add_name CDATA #IMPLIED>

<!ELEMENT enchant_options (level)*>
<!ELEMENT level (option)*>
<!ATTLIST level
	value CDATA #REQUIRED>
<!ELEMENT option (#PCDATA)>
<!ATTLIST option
	id CDATA #REQUIRED>

<!ELEMENT equip (slot)*>
<!ELEMENT slot (#PCDATA)>
<!ATTLIST slot
	id CDATA #REQUIRED>

<!ELEMENT cond (player|target|using|zone|or|not|and)*>
<!ATTLIST cond
	msgId CDATA #IMPLIED>
<!ELEMENT or (player|target|using|zone|or|not|and)*>
<!ELEMENT not (player|target|using|zone|or|not|and)*>
<!ELEMENT and (player|target|using|zone|or|not|and)*>
<!ELEMENT player (#PCDATA)>
<!ATTLIST player
	residence CDATA #IMPLIED
	olympiad CDATA #IMPLIED
	race CDATA #IMPLIED
	instance_zone CDATA #IMPLIED
	is_clan_leader CDATA #IMPLIED
	sex CDATA #IMPLIED
	castle_type CDATA #IMPLIED
	classId CDATA #IMPLIED
	minLevel CDATA #IMPLIED
	max_level CDATA #IMPLIED
	avail_max_sp CDATA #IMPLIED
	quest_state CDATA #IMPLIED
	min_pledge_rank CDATA #IMPLIED
	class_type CDATA #IMPLIED
	min_clan_level CDATA #IMPLIED
	isFlagged CDATA #IMPLIED
	is_hero CDATA #IMPLIED
	is_chaotic CDATA #IMPLIED
	minimum_magic_lamp_points CDATA #IMPLIED
	maximum_magic_lamp_points CDATA #IMPLIED
	minimum_random_craft_points CDATA #IMPLIED
	maximum_random_craft_points CDATA #IMPLIED
	minimum_sayhas_grace CDATA #IMPLIED
	maximum_sayhas_grace CDATA #IMPLIED>
<!ELEMENT target (#PCDATA)>
<!ATTLIST target
	is_pet_feed CDATA #IMPLIED
	type CDATA #IMPLIED>
<!ELEMENT using (#PCDATA)>
<!ATTLIST using
	slotitem CDATA #REQUIRED>
<!ELEMENT zone (#PCDATA)>
<!ATTLIST zone
	type CDATA #IMPLIED
	name CDATA #IMPLIED>

<!ELEMENT for (add|set|mul)*>
<!ELEMENT add (player|target|using|zone|or|not|and)*>
<!ATTLIST add
	order CDATA #REQUIRED
	stat CDATA #REQUIRED
	value CDATA #REQUIRED>

<!ELEMENT attributes (attribute)*>
<!ELEMENT attribute (#PCDATA)>
<!ATTLIST attribute
	element CDATA #REQUIRED
	value CDATA #REQUIRED>

	<!ELEMENT capsuled_items (capsuled_item)*>

		<!ELEMENT capsuled_item (#PCDATA)>
		<!ATTLIST capsuled_item
			id CDATA #REQUIRED
			min_count CDATA #REQUIRED
			max_count CDATA #REQUIRED
			chance CDATA #REQUIRED
			enchant CDATA #IMPLIED
			announce CDATA #IMPLIED>

	<!ELEMENT create_items (create_item)*>

	<!ELEMENT create_item_groups (create_item_group)*>
	
		<!ELEMENT create_item_group (create_item)*>

		<!ELEMENT create_item (#PCDATA)>
		<!ATTLIST create_item
			id CDATA #REQUIRED
			count CDATA #REQUIRED
			chance CDATA #IMPLIED
			enchant CDATA #IMPLIED>

<!ELEMENT mul (player|target|using|zone)*>
<!ATTLIST mul
	order CDATA #REQUIRED
	stat CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT set (player|target|using|zone|or|not|and)*>
<!ATTLIST set
	name CDATA #IMPLIED
	order CDATA #IMPLIED
	stat CDATA #IMPLIED
	value CDATA #REQUIRED>

<!ELEMENT skills (skill|enchant_skill)*>

	<!ELEMENT skill (#PCDATA)>
	<!ATTLIST skill
		id CDATA #REQUIRED
		level CDATA #REQUIRED>

	<!ELEMENT enchant_skill (#PCDATA)>
	<!ATTLIST enchant_skill
		id CDATA #REQUIRED
		level CDATA #REQUIRED
		enchant CDATA #REQUIRED>

<!ELEMENT triggers (trigger)*>
<!ELEMENT trigger (#PCDATA)>
<!ATTLIST trigger
	id CDATA #REQUIRED
	level CDATA #REQUIRED
	type CDATA #REQUIRED
	chance CDATA #REQUIRED
	cancel_effects_on_remove CDATA #IMPLIED>

<!ELEMENT agathion_data (enchant)*>

<!ELEMENT enchant (main_skills|sub_skills)*>
<!ATTLIST enchant
	level CDATA #REQUIRED>

<!ELEMENT main_skills (skill)*>
<!ELEMENT sub_skills (skill)*>

=== rootmp/multiprof/dist/gameserver/data/parser/items/8200-8299.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "item.dtd">
<list>
	<weapon id="8203" name="Monster Only (Venom Sword) - Not Available" add_name="Not Available">
		<set name="random_damage" value="10"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.etc_ertheia2"/>
		<set name="type" value="DUAL"/>
		<set name="weight" value="1560"/>
		<set name="soulshots" value="1"/>
		<set name="spiritshots" value="1"/>
		<set name="rnd_dam" value="10"/>
		<equip>
			<slot id="LEFT_RIGHT_HAND"/>
		</equip>
		<for>
			<set stat="basePAtkSpd" order="0x08" value="325"/>
			<set stat="basePCritRate" order="0x08" value="80"/>
		</for>
	</weapon>
	<weapon id="8204" name="Monster Only (Follower of Frintezza Calibur)">
		<set name="random_damage" value="10"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.weapon_monster_i00"/>
		<set name="type" value="SWORD"/>
		<set name="weight" value="1560"/>
		<set name="soulshots" value="1"/>
		<set name="spiritshots" value="1"/>
		<set name="rnd_dam" value="10"/>
		<equip>
			<slot id="RIGHT_HAND"/>
		</equip>
		<for>
			<set stat="basePAtkSpd" order="0x08" value="379"/>
			<set stat="basePCritRate" order="0x08" value="80"/>
		</for>
	</weapon>
	<weapon id="8222" name="Monster Only (Follower of Frintezza Tran Calibur)">
		<set name="random_damage" value="10"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.weapon_monster_i00"/>
		<set name="type" value="SWORD"/>
		<set name="weight" value="1560"/>
		<set name="soulshots" value="1"/>
		<set name="spiritshots" value="1"/>
		<set name="rnd_dam" value="10"/>
		<equip>
			<slot id="RIGHT_HAND"/>
		</equip>
		<for>
			<set stat="basePAtkSpd" order="0x08" value="379"/>
			<set stat="basePCritRate" order="0x08" value="80"/>
		</for>
	</weapon>
	<etcitem id="8294" name="Recipe: Steel Sword (100%)">
		<set name="grind_commission" value="103"/>
		<set name="grind_point" value="5112"/>
		<set name="type" value="RECIPE"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.etc_recipe_blue_i00"/>
		<set name="price" value="102250"/>
		<set name="stackable" value="true"/>
		<set name="weight" value="30"/>
	</etcitem>
	<etcitem id="8299" name="Recipe: Infernal Master (100%)">
		<set name="grind_commission" value="3525"/>
		<set name="grind_point" value="176225"/>
		<set name="price" value="3524500"/>
		<set name="icon" value="icon.etc_recipe_violet_i00"/>
		<set name="weight" value="30"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
</list>

=== rootmp/multiprof/dist/gameserver/data/parser/items/20700-20799.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "item.dtd">
<list>
	<etcitem id="20728" name="Scroll: Summon Lucky Lamp">
		<set name="mailable" value="false"/>
		<set name="clan_warehouseable" value="false"/>
		<set name="reuse_delay" value="14400000"/>
		<set name="is_olympiad_can_use" value="false"/>
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="icon" value="BranchSys.icon.br_lamp_orange_i00"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<armor id="20792" name="Flavorful Cheese Hat - Not Available" add_name="Not Available">
		<set name="is_olympiad_can_use" value="false"/>
		<set name="sellable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.etc_ertheia2"/>
		<set name="type" value="NONE"/>
		<set name="weight" value="10"/>
		<equip>
			<slot id="HAIR_ALL"/>
		</equip>
	</armor>
	<armor id="20793" name="Sweet Cheese Hat - Not Available" add_name="Not Available">
		<set name="is_olympiad_can_use" value="false"/>
		<set name="sellable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.etc_ertheia2"/>
		<set name="type" value="NONE"/>
		<set name="weight" value="10"/>
		<equip>
			<slot id="HAIR_ALL"/>
		</equip>
	</armor>
</list>

=== rootmp/multiprof/dist/gameserver/data/parser/items/36400-36499.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "item.dtd">
<list>
	<armor id="36413" name="Single Mesh Armor" add_name="Sealed">
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.armor_t2000_ul_i00"/>
		<set name="type" value="HEAVY"/>
		<set name="weight" value="1000"/>
		<set name="tradeable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="destroyable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="sellable" value="false"/>
		<set name="private_warehouseable" value="false"/>
		<set name="clan_warehouseable" value="false"/>
		<set name="mailable" value="false"/>
		<equip>
			<slot id="FORMAL_WEAR"/>
		</equip>
	</armor>
</list>

=== rootmp/multiprof/dist/gameserver/data/parser/items/6500-6599.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "item.dtd">
<list>
	<etcitem id="6569" name="Protecting Scroll: Enchant A-grade Weapon">
		<set name="is_olympiad_can_use" value="false"/>
		<set name="icon" value="icon.etc_blessed_scrl_of_ench_wp_a_i04"/>
		<set name="type" value="SCROLL_ENCHANT_WEAPON"/>
		<set name="crystal_type" value="NONE"/>
		<set name="stackable" value="true"/>
		<set name="weight" value="0"/>
	</etcitem>
	<etcitem id="6570" name="Protecting Scroll: Enchant A-grade Armor">
		<set name="is_olympiad_can_use" value="false"/>
		<set name="icon" value="icon.etc_blessed_scrl_of_ench_am_a_i04"/>
		<set name="type" value="SCROLL_ENCHANT_ARMOR"/>
		<set name="crystal_type" value="NONE"/>
		<set name="stackable" value="true"/>
		<set name="weight" value="0"/>
	</etcitem>
	<etcitem id="6571" name="Protecting Scroll: Enchant B-grade Weapon">
		<set name="is_olympiad_can_use" value="false"/>
		<set name="sellable" value="false"/>
		<set name="type" value="SCROLL_ENCHANT_WEAPON"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.etc_blessed_scrl_of_ench_wp_b_i03"/>
		<set name="stackable" value="true"/>
		<set name="weight" value="0"/>
	</etcitem>
	<etcitem id="6572" name="Protecting Scroll: Enchant B-grade Armor">
		<set name="is_olympiad_can_use" value="false"/>
		<set name="sellable" value="false"/>
		<set name="type" value="SCROLL_ENCHANT_ARMOR"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.etc_blessed_scrl_of_ench_am_b_i03"/>
		<set name="stackable" value="true"/>
		<set name="weight" value="0"/>
	</etcitem>
	<etcitem id="6573" name="Protecting Scroll: Enchant C-grade Weapon">
		<set name="is_olympiad_can_use" value="false"/>
		<set name="sellable" value="false"/>
		<set name="type" value="SCROLL_ENCHANT_WEAPON"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.etc_blessed_scrl_of_ench_wp_c_i02"/>
		<set name="stackable" value="true"/>
		<set name="weight" value="0"/>
	</etcitem>
	<etcitem id="6574" name="Protecting Scroll: Enchant C-grade Armor">
		<set name="is_olympiad_can_use" value="false"/>
		<set name="sellable" value="false"/>
		<set name="type" value="SCROLL_ENCHANT_ARMOR"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.etc_blessed_scrl_of_ench_am_c_i02"/>
		<set name="stackable" value="true"/>
		<set name="weight" value="0"/>
	</etcitem>
	<etcitem id="6575" name="Protecting Scroll: Enchant D-grade Weapon">
		<set name="is_olympiad_can_use" value="false"/>
		<set name="sellable" value="false"/>
		<set name="type" value="SCROLL_ENCHANT_WEAPON"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.etc_blessed_scrl_of_ench_wp_d_i01"/>
		<set name="stackable" value="true"/>
		<set name="weight" value="0"/>
	</etcitem>
	<etcitem id="6576" name="Protecting Scroll: Enchant D-grade Armor">
		<set name="is_olympiad_can_use" value="false"/>
		<set name="sellable" value="false"/>
		<set name="type" value="SCROLL_ENCHANT_ARMOR"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.etc_blessed_scrl_of_ench_am_d_i01"/>
		<set name="stackable" value="true"/>
		<set name="weight" value="0"/>
	</etcitem>
	<etcitem id="6577" name="Protecting Scroll: Enchant S-grade Weapon">
		<set name="grind_commission" value="300000"/>
		<set name="grind_point" value="15000000"/>
		<set name="price" value="30000000"/>
		<set name="type" value="SCROLL_ENCHANT_WEAPON"/>
		<set name="icon" value="icon.etc_blessed_scrl_of_ench_wp_s_i05"/>
		<set name="weight" value="0"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="6578" name="Protecting Scroll: Enchant S-grade Armor">
		<set name="grind_commission" value="45000"/>
		<set name="grind_point" value="2250000"/>
		<set name="price" value="4500000"/>
		<set name="type" value="SCROLL_ENCHANT_ARMOR"/>
		<set name="icon" value="icon.etc_blessed_scrl_of_ench_am_s_i05"/>
		<set name="weight" value="0"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<weapon id="6579" name="Arcana Mace">
		<set name="freightable" value="true"/>
		<set name="random_damage" value="19"/>
		<set name="grind_commission" value="427594"/>
		<set name="grind_point" value="21379700"/>
		<set name="damage_range" value="0;0;40;120"/>
		<set name="variation_group_id" value="2"/>
		<set name="is_magic_weapon" value="true"/>
		<set name="price" value="42759400"/>
		<set name="crystal_count" value="1368"/>
		<set name="crystal_type" value="S"/>
		<set name="icon" value="icon.weapon_arcana_mace_i00"/>
		<set name="type" value="BLUNT"/>
		<set name="weight" value="1300"/>
		<set name="soulshots" value="4"/>
		<set name="spiritshots" value="4"/>
		<set name="rnd_dam" value="19"/>
		<equip>
			<slot id="RIGHT_HAND"/>
		</equip>
		<for>
			<add stat="pAtk" order="0x10" value="225"/>
			<add stat="mAtk" order="0x10" value="201"/>
			<set stat="basePAtkSpd" order="0x08" value="379"/>
			<set stat="basePCritRate" order="0x08" value="60"/>
			<add stat="pAccCombat" order="0x10" value="8"/>
		</for>
	</weapon>
	<weapon id="6580" name="Tallum Blade*Dark Legion's Edge">
		<set name="freightable" value="true"/>
		<set name="random_damage" value="10"/>
		<set name="grind_commission" value="427594"/>
		<set name="grind_point" value="21379700"/>
		<set name="damage_range" value="0;0;44;120"/>
		<set name="variation_group_id" value="2"/>
		<set name="crystal_count" value="1368"/>
		<set name="crystal_type" value="S"/>
		<set name="icon" value="icon.weapon_dual_sword_i00"/>
		<set name="price" value="42759400"/>
		<set name="type" value="DUAL"/>
		<set name="weight" value="2080"/>
		<set name="soulshots" value="4"/>
		<set name="spiritshots" value="4"/>
		<set name="rnd_dam" value="10"/>
		<equip>
			<slot id="LEFT_RIGHT_HAND"/>
		</equip>
		<for>
			<add stat="pAtk" order="0x10" value="342"/>
			<add stat="mAtk" order="0x10" value="151"/>
			<set stat="basePAtkSpd" order="0x08" value="325"/>
			<set stat="basePCritRate" order="0x08" value="80"/>
		</for>
	</weapon>
</list>

=== rootmp/multiprof/dist/gameserver/data/parser/items/23100-23199.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "item.dtd">
<list>
	<armor id="23173" name="Alluring Swimsuit - Not Available" add_name="Not Available">
		<set name="sellable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.etc_ertheia2"/>
		<set name="type" value="HEAVY"/>
		<equip>
			<slot id="FORMAL_WEAR"/>
		</equip>
	</armor>
</list>

=== rootmp/multiprof/dist/gameserver/data/parser/items/37500-37599.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "item.dtd">
<list>
	<armor id="37533" name="NC Messenger's Hat" add_name="Sealed">
		<set name="freightable" value="true"/>
		<set name="mailable" value="false"/>
		<set name="clan_warehouseable" value="false"/>
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.nc_hair_acc"/>
		<set name="type" value="NONE"/>
		<equip>
			<slot id="HAIR_ALL"/>
		</equip>
	</armor>
	<armor id="37534" name="Santa Outfit" add_name="Sealed">
		<set name="mailable" value="false"/>
		<set name="clan_warehouseable" value="false"/>
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.armor_ev_santas_clothes"/>
		<set name="type" value="HEAVY"/>
		<equip>
			<slot id="FORMAL_WEAR"/>
		</equip>
	</armor>
	<armor id="37535" name="Santa Hat" add_name="Sealed">
		<set name="mailable" value="false"/>
		<set name="clan_warehouseable" value="false"/>
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.accessory_santas_cap_i00"/>
		<set name="type" value="NONE"/>
		<equip>
			<slot id="HAIR_ALL"/>
		</equip>
	</armor>
	<etcitem id="37543" name="Snowy Squash Nectar">
		<set name="is_olympiad_can_use" value="false"/>
		<set name="handler" value="SkillsReduce"/>
		<set name="sellable" value="false"/>
		<set name="icon" value="icon.etc_nectar_i01"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
		<skills>
			<skill id="17110" level="1"/>	<!--Нектар Снежной Тыквы-->
		</skills>
	</etcitem>
	<etcitem id="37544" name="Snowball">
		<set name="sellable" value="false"/>
		<set name="icon" value="BranchSys2.icon.g_illumination_white"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="37545" name="Large Snowball">
		<set name="sellable" value="false"/>
		<set name="icon" value="BranchSys2.icon.g_illumination_white"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="37546" name="Rudolph's Gift 2015" add_name="Lv. 1">
		<set name="icon" value="icon.etc_pi_gift_box_i04"/>
		<set name="weight" value="10"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="37547" name="Rudolph's Gift 2015" add_name="Lv. 2">
		<set name="icon" value="icon.etc_pi_gift_box_i04"/>
		<set name="weight" value="10"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="37548" name="Rudolph's Gift 2015" add_name="Lv. 3">
		<set name="icon" value="icon.etc_pi_gift_box_i04"/>
		<set name="weight" value="10"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="37549" name="Rudolph's Gift 2015" add_name="Lv. 4">
		<set name="icon" value="icon.etc_pi_gift_box_i04"/>
		<set name="weight" value="10"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="37550" name="Snowman's Buff">
		<set name="icon" value="icon.weapon_snowman_stick_i00"/>
		<set name="weight" value="120"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="37551" name="Christmas Present">
		<set name="sellable" value="false"/>
		<set name="icon" value="icon.etc_pi_gift_box_i04"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="37552" name="Snowy Squash Seed">
		<set name="handler" value="SkillsReduce"/>
		<set name="icon" value="icon.etc_gourd_i10"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
		<skills>
			<skill id="17111" level="1"/>	<!-- Семечко Снежной Тыквы-->
		</skills>
	</etcitem>
	<etcitem id="37553" name="Large Snowy Squash Seed">
		<set name="handler" value="SkillsReduce"/>
		<set name="icon" value="icon.etc_gourd_i11"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
		<skills>
			<skill id="17112" level="1"/>	<!-- Семечко Снежной Большой Тыквы-->
		</skills>
	</etcitem>
</list>

=== rootmp/multiprof/dist/gameserver/data/parser/items/34000-34099.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "item.dtd">
<list>
	<etcitem id="34070" name="Scroll: Enchant C-grade Weapon" add_name="Sealed">
		<set name="mailable" value="false"/>
		<set name="clan_warehouseable" value="false"/>
		<set name="is_olympiad_can_use" value="false"/>
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="icon" value="icon.etc_scroll_of_enchant_weapon_i02"/>
		<set name="weight" value="0"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
		<set name="type" value="SCROLL_ENCHANT_WEAPON"/>
	</etcitem>
	<etcitem id="34072" name="Scroll: Enchant D-grade Weapon" add_name="Sealed">
		<set name="mailable" value="false"/>
		<set name="clan_warehouseable" value="false"/>
		<set name="is_olympiad_can_use" value="false"/>
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="icon" value="icon.etc_scroll_of_enchant_weapon_i01"/>
		<set name="weight" value="0"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
		<set name="type" value="SCROLL_ENCHANT_WEAPON"/>
	</etcitem>
</list>
