=== rootmp/multiprof/dist/gameserver/data/parser/zones/zone/zone.dtd
<!ELEMENT list (zone)*>
<!ELEMENT zone (polygon|circle|rectangle|banned_polygon|banned_circle|banned_rectangle|map|banned_map|set|restart_point|PKrestart_point|for)*>
<!ATTLIST zone
	name CDATA #REQUIRED
	type CDATA #REQUIRED>
<!ELEMENT polygon (coords)*>
<!ELEMENT circle (coords)*>
<!ELEMENT rectangle (coords)*>
<!ELEMENT restart_point (coords)*>
<!ELEMENT PKrestart_point (coords)*>
<!ELEMENT banned_polygon (coords)*>
<!ELEMENT banned_circle (coords)*>
<!ELEMENT banned_rectangle (coords)*>
<!ELEMENT map (#PCDATA)>
<!ATTLIST map
	value CDATA #REQUIRED>
<!ELEMENT banned_map (#PCDATA)>
<!ATTLIST banned_map
	value CDATA #REQUIRED>
<!ELEMENT coords (#PCDATA)>
<!ATTLIST coords
	loc CDATA #REQUIRED>
<!ATTLIST circle
	loc CDATA #IMPLIED>
<!ATTLIST banned_circle
	loc CDATA #IMPLIED>

		<!ELEMENT set (player|target|using|has|game|or|not|and)*>
		<!ATTLIST set
			name CDATA #IMPLIED
			order CDATA #IMPLIED
			stat CDATA #IMPLIED
			value CDATA #REQUIRED>

		<!ELEMENT for (add|set|mul|sub)*>

			<!ELEMENT add (player|target|using|has|game|or|not|and)*>
			<!ATTLIST add
				order CDATA #REQUIRED
				stat CDATA #REQUIRED
				value CDATA #REQUIRED>

			<!ELEMENT mul (player|target|using|has|game|or|not|and)*>
			<!ATTLIST mul
				order CDATA #REQUIRED
				stat CDATA #REQUIRED
				value CDATA #REQUIRED>

			<!ELEMENT sub (player|target|using|has|game|or|not|and)*>
			<!ATTLIST sub
				order CDATA #REQUIRED
				stat CDATA #REQUIRED
				value CDATA #REQUIRED>

				<!ELEMENT or (player|target|using|has|game|or|not|and)*>

				<!ELEMENT not (player|target|using|has|game|or|not|and)*>

				<!ELEMENT and (player|target|using|has|game|or|not|and)*>

				<!ELEMENT player (#PCDATA)>
				<!ATTLIST player
					residence CDATA #IMPLIED
					olympiad CDATA #IMPLIED
					race CDATA #IMPLIED
					instance_zone CDATA #IMPLIED
					is_clan_leader CDATA #IMPLIED
					is_hero CDATA #IMPLIED
					sex CDATA #IMPLIED
					classId CDATA #IMPLIED
					minLevel CDATA #IMPLIED
					max_level CDATA #IMPLIED
					avail_max_sp CDATA #IMPLIED
					quest_state CDATA #IMPLIED
					min_pledge_rank CDATA #IMPLIED
					class_type CDATA #IMPLIED
					summon_siege_golem CDATA #IMPLIED
					running CDATA #IMPLIED
					percentHP CDATA #IMPLIED
					resting CDATA #IMPLIED
					max_level CDATA #IMPLIED
					maxPK CDATA #IMPLIED
					percentMP CDATA #IMPLIED
					moving CDATA #IMPLIED
					standing CDATA #IMPLIED
					damage CDATA #IMPLIED
					percentCP CDATA #IMPLIED
					direction CDATA #IMPLIED
					riding CDATA #IMPLIED
					flying CDATA #IMPLIED
					castle_type CDATA #IMPLIED
					chaos_festival CDATA #IMPLIED
					min_clan_level CDATA #IMPLIED
					has_abnormal_type CDATA #IMPLIED
					has_summon_id CDATA #IMPLIED
					can_transform CDATA #IMPLIED
					can_untransform CDATA #IMPLIED
					agathion CDATA #IMPLIED
					hasBuffId CDATA #IMPLIED
					flyingTransform CDATA #IMPLIED
					isFlagged CDATA #IMPLIED
					can_learn_skill CDATA #IMPLIED
					is_chaotic CDATA #IMPLIED>

				<!ELEMENT target (#PCDATA)>
				<!ATTLIST target
					is_pet_feed CDATA #IMPLIED
					type CDATA #IMPLIED
					race CDATA #IMPLIED
					hasForbiddenSkill CDATA #IMPLIED
					mobId CDATA #IMPLIED
					npc_class CDATA #IMPLIED
					castledoor CDATA #IMPLIED
					direction CDATA #IMPLIED
					percentHP CDATA #IMPLIED
					has_abnormal_type CDATA #IMPLIED
					forbiddenClassIds CDATA #IMPLIED
					min_distance CDATA #IMPLIED
					hasBuffId CDATA #IMPLIED
					playerRace CDATA #IMPLIED>

				<!ELEMENT using (#PCDATA)>
				<!ATTLIST using
					slotitem CDATA #IMPLIED
					kind CDATA #IMPLIED
					armor CDATA #IMPLIED
					weapon CDATA #IMPLIED
					skill CDATA #IMPLIED>

				<!ELEMENT game (#PCDATA)>
				<!ATTLIST game
					night CDATA #IMPLIED>

				<!ELEMENT has (#PCDATA)>
				<!ATTLIST has
					skill CDATA #IMPLIED>

=== rootmp/multiprof/dist/gameserver/data/parser/zones/zone/INSTANT_RESIDENCE.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "zone.dtd">
<!--AUTHOR: Bonux-->
<list>
	<zone name="[InstantAgit_peace_zone1]" type="peace_zone">
		<set name="enabled" value="false"/>
		<polygon>
			<coords loc="-117545 -122814 -6120 -5620"/>
			<coords loc="-116462 -122825 -6120 -5620"/>
			<coords loc="-116460 -121354 -6120 -5620"/>
			<coords loc="-117542 -121343 -6120 -5620"/>
		</polygon>
	</zone>
	<zone name="[InstantAgit_peace_zone2]" type="peace_zone">
		<set name="enabled" value="false"/>
		<polygon>
			<coords loc="-122820 -122819 -5950 -5450"/>
			<coords loc="-121738 -122830 -5950 -5450"/>
			<coords loc="-121735 -121359 -5950 -5450"/>
			<coords loc="-122817 -121348 -5950 -5450"/>
		</polygon>
	</zone>
	<zone name="[InstantAgit_peace_zone3]" type="peace_zone">
		<set name="enabled" value="false"/>
		<polygon>
			<coords loc="-112262 -122818 -6120 -5620"/>
			<coords loc="-111180 -122829 -6120 -5620"/>
			<coords loc="-111177 -121358 -6120 -5620"/>
			<coords loc="-112259 -121347 -6120 -5620"/>
		</polygon>
	</zone>
	<zone name="[InstantAgit_peace_zone4]" type="peace_zone">
		<set name="enabled" value="false"/>
		<polygon>
			<coords loc="-117598 -117174 -6120 -5620"/>
			<coords loc="-115754 -117188 -6120 -5620"/>
			<coords loc="-115753 -115924 -6120 -5620"/>
			<coords loc="-117600 -115926 -6120 -5620"/>
		</polygon>
	</zone>
	<zone name="[InstantAgit_peace_zone5]" type="peace_zone">
		<set name="enabled" value="false"/>
		<polygon>
			<coords loc="-122770 -117171 -6120 -5620"/>
			<coords loc="-120927 -117186 -6120 -5620"/>
			<coords loc="-120926 -115921 -6120 -5620"/>
			<coords loc="-122772 -115923 -6120 -5620"/>
		</polygon>
	</zone>
	<zone name="[InstantAgit_peace_zone6]" type="peace_zone">
		<set name="enabled" value="false"/>
		<polygon>
			<coords loc="-112290 -117174 -6120 -5620"/>
			<coords loc="-110447 -117188 -6120 -5620"/>
			<coords loc="-110446 -115924 -6120 -5620"/>
			<coords loc="-112293 -115926 -6120 -5620"/>
		</polygon>
	</zone>
	<zone name="[InstantAgit_peace_zone7]" type="peace_zone">
		<set name="enabled" value="false"/>
		<polygon>
			<coords loc="-117620 -111833 -6120 -5620"/>
			<coords loc="-116081 -111833 -6120 -5620"/>
			<coords loc="-116066 -110661 -6120 -5620"/>
			<coords loc="-117620 -110663 -6120 -5620"/>
		</polygon>
	</zone>
	<zone name="[InstantAgit_peace_zone8]" type="peace_zone">
		<set name="enabled" value="false"/>
		<polygon>
			<coords loc="-122847 -111833 -6120 -5620"/>
			<coords loc="-121308 -111833 -6120 -5620"/>
			<coords loc="-121293 -110661 -6120 -5620"/>
			<coords loc="-122847 -110663 -6120 -5620"/>
		</polygon>
	</zone>
	<zone name="[InstantAgit_peace_zone9]" type="peace_zone">
		<set name="enabled" value="false"/>
		<polygon>
			<coords loc="-112273 -111833 -6120 -5620"/>
			<coords loc="-110734 -111833 -6120 -5620"/>
			<coords loc="-110718 -110660 -6120 -5620"/>
			<coords loc="-112272 -110663 -6120 -5620"/>
		</polygon>
	</zone>
</list>

=== rootmp/multiprof/dist/gameserver/data/parser/zones/zone/epic.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "zone.dtd">
<list>
	<zone name="[baium_epic]" type="epic" >
		<polygon>
			<coords loc="116616 17576 10032 10232"/>
			<coords loc="117064 16552 10032 10232"/>
			<coords loc="117032 15592 10032 10232"/>
			<coords loc="116664 14632 10032 10232"/>
			<coords loc="116024 14008 10032 10232"/>
			<coords loc="115128 13640 10032 10232"/>
			<coords loc="114136 13624 10032 10232"/>
			<coords loc="113256 13992 10032 10232"/>
			<coords loc="112568 14664 10032 10232"/>
			<coords loc="112216 15592 10032 10232"/>
			<coords loc="112216 16552 10032 10232"/>
			<coords loc="112600 17432 10032 10232"/>
			<coords loc="113288 18120 10032 10232"/>
			<coords loc="114152 18472 10032 10232"/>
			<coords loc="115144 18488 10032 10232"/>
			<coords loc="116152 18024 10032 10232"/>
		</polygon>
	</zone>
	<zone name="[antharas_epic]" type="epic" >
		<polygon>
			<coords loc="181552 116384 -7704 -7604"/>
			<coords loc="179849 118366 -7704 -7604"/>
			<coords loc="175896 118465 -7704 -7604"/>

			<coords loc="175320 118088 -7704 -7604"/>
			<coords loc="173816 115656 -7704 -7604"/>
			<coords loc="173720 114120 -7704 -7604"/>
			<coords loc="175160 111848 -7704 -7604"/>
			<coords loc="175704 111304 -7704 -7604"/>
			<coords loc="176408 111192 -7704 -7604"/>
			<coords loc="179432 111192 -7704 -7604"/>
			<coords loc="179832 111320 -7704 -7604"/>
			<coords loc="180072 111592 -7704 -7604"/>

			<!-- <coords loc="175328 118128 -7704 -7604"/>
			<coords loc="173728 115536 -7704 -7604"/>
			<coords loc="173609 114700 -7704 -7604"/>
			<coords loc="173712 114128 -7704 -7604"/>
			<coords loc="175385 111503 -7704 -7604"/>
			<coords loc="176016 111216 -7704 -7604"/>
			<coords loc="179896 111348 -7704 -7604"/>
			<coords loc="180730 112225 -7704 -7604"/> -->

			<coords loc="182199 114122 -7728 -7628"/>
			<coords loc="184369 114148 -8216 -8116"/>
			<coords loc="186526 113634 -8216 -8116"/>
			<coords loc="187279 114909 -8216 -8116"/>
			<coords loc="186627 115882 -8216 -8116"/>
			<coords loc="184224 115472 -8208 -8108"/>
			<coords loc="182272 115584 -7744 -7644"/>
		</polygon>
	</zone>
	<zone name="[antharas_cave]" type="epic">
		<set name="enabled" value="true"/>
		<polygon>
			<coords loc="126552 120312 -5000 -2000"/>
			<coords loc="128472 121496 -5000 -2000"/>
			<coords loc="129544 122328 -5000 -2000"/>
			<coords loc="129960 123592 -5000 -2000"/>
			<coords loc="127368 127432 -5000 -2000"/>
			<coords loc="125224 127032 -5000 -2000"/>
			<coords loc="125176 127000 -5000 -2000"/>
			<coords loc="121944 123928 -5000 -2000"/>
			<coords loc="122120 122344 -5000 -2000"/>
			<coords loc="125352 120360 -5000 -2000"/>
		</polygon>
	</zone>
	<zone name="[queen_ant_epic]" type="epic" >
		<set name="levelLimit" value="48"/>
		<set name="tele" value="-25464 172424 -4203"/>
		<polygon>
			<coords loc="-23176 185080 -6000 -5500"/>
			<coords loc="-20104 185080 -6000 -5500"/>
			<coords loc="-20104 177928 -6000 -5500"/>
			<coords loc="-23176 177928 -6000 -5500"/>
		</polygon>
	</zone>
</list>
