=== rootmp/multiprof/dist/gameserver/data/parser/skills/skill.dtd
<!ELEMENT list (skill)*>

	<!ELEMENT skill  (set|table|for|cond|triggers|enchant|restoration)*>
	<!ATTLIST skill
		id CDATA #REQUIRED
		levels CDATA #REQUIRED
		name CDATA #REQUIRED>

		<!ELEMENT set (player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST set
			name CDATA #IMPLIED
			order CDATA #IMPLIED
			stat CDATA #IMPLIED
			value CDATA #REQUIRED>

		<!ELEMENT table (#PCDATA)>
		<!ATTLIST table
			name CDATA #REQUIRED>

		<!ELEMENT start_effect (def|add|stat_effect|p_critical_damage|p_magic_critical_dmg|p_skill_critical_damage|p_heal_effect|p_elemental_exp_rate|p_elemental_attack|p_elemental_defence|p_elemental_crit_rate|p_elemental_crit_attack|p_attack_trait|p_defence_trait|p_vampiric_attack|p_mp_vampiric_attack|set|mul|div|sub|cond|triggers|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST start_effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			interval CDATA #IMPLIED
			instant CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED>

		<!ELEMENT tick_effect (def|add|stat_effect|p_critical_damage|p_magic_critical_dmg|p_skill_critical_damage|p_heal_effect|p_elemental_exp_rate|p_elemental_attack|p_elemental_defence|p_elemental_crit_rate|p_elemental_crit_attack|p_attack_trait|p_defence_trait|p_vampiric_attack|p_mp_vampiric_attack|set|mul|div|sub|cond|triggers|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST tick_effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			interval CDATA #IMPLIED
			instant CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED>

		<!ELEMENT self_effect (def|add|stat_effect|p_critical_damage|p_magic_critical_dmg|p_skill_critical_damage|p_heal_effect|p_elemental_exp_rate|p_elemental_attack|p_elemental_defence|p_elemental_crit_rate|p_elemental_crit_attack|p_attack_trait|p_defence_trait|p_vampiric_attack|p_mp_vampiric_attack|set|mul|div|sub|cond|triggers|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST self_effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			interval CDATA #IMPLIED
			instant CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED
			type CDATA #IMPLIED>

		<!ELEMENT effect (def|add|stat_effect|p_critical_damage|p_magic_critical_dmg|p_skill_critical_damage|p_heal_effect|p_elemental_exp_rate|p_elemental_attack|p_elemental_defence|p_elemental_crit_rate|p_elemental_crit_attack|p_attack_trait|p_defence_trait|p_vampiric_attack|p_mp_vampiric_attack|set|mul|div|sub|cond|triggers|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			interval CDATA #IMPLIED
			instant CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED
			type CDATA #IMPLIED>

		<!ELEMENT pvp_effect (def|add|stat_effect|p_critical_damage|p_magic_critical_dmg|p_skill_critical_damage|p_heal_effect|p_elemental_exp_rate|p_elemental_attack|p_elemental_defence|p_elemental_crit_rate|p_elemental_crit_attack|p_attack_trait|p_defence_trait|p_vampiric_attack|p_mp_vampiric_attack|set|mul|div|sub|cond|triggers|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST pvp_effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			interval CDATA #IMPLIED
			instant CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED
			type CDATA #IMPLIED>

		<!ELEMENT pve_effect (def|add|stat_effect|p_critical_damage|p_magic_critical_dmg|p_skill_critical_damage|p_heal_effect|p_elemental_exp_rate|p_elemental_attack|p_elemental_defence|p_elemental_crit_rate|p_elemental_crit_attack|p_attack_trait|p_defence_trait|p_vampiric_attack|p_mp_vampiric_attack|set|mul|div|sub|cond|triggers|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST pve_effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			interval CDATA #IMPLIED
			instant CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED
			type CDATA #IMPLIED>

		<!ELEMENT end_effect (def|add|stat_effect|p_critical_damage|p_magic_critical_dmg|p_skill_critical_damage|p_heal_effect|p_elemental_exp_rate|p_elemental_attack|p_elemental_defence|p_elemental_crit_rate|p_elemental_crit_attack|p_attack_trait|p_defence_trait|p_vampiric_attack|p_mp_vampiric_attack|set|mul|div|sub|cond|triggers|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST end_effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED>

			<!ELEMENT def (#PCDATA)>
			<!ATTLIST def
				name CDATA #REQUIRED
				value CDATA #REQUIRED>

		<!ELEMENT for (add|stat_effect|p_critical_damage|p_magic_critical_dmg|p_skill_critical_damage|p_heal_effect|p_elemental_exp_rate|p_elemental_attack|p_elemental_defence|p_elemental_crit_rate|p_elemental_crit_attack|p_attack_trait|p_defence_trait|p_vampiric_attack|p_mp_vampiric_attack|set|mul|div|sub|start_effect|tick_effect|self_effect|effect|pvp_effect|pve_effect|end_effect)*>

			<!ELEMENT add (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST add
				order CDATA #IMPLIED
				stat CDATA #REQUIRED
				value CDATA #REQUIRED>

			<!ELEMENT stat_effect (set)*>
			<!ATTLIST stat_effect
				name CDATA #REQUIRED
				value CDATA #IMPLIED
				type CDATA #IMPLIED>

			<!ELEMENT p_critical_damage (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST p_critical_damage
				value CDATA #REQUIRED
				type CDATA #REQUIRED>

			<!ELEMENT p_magic_critical_dmg (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST p_magic_critical_dmg
				value CDATA #REQUIRED
				type CDATA #REQUIRED>

			<!ELEMENT p_skill_critical_damage (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST p_skill_critical_damage
				value CDATA #REQUIRED
				type CDATA #REQUIRED>

			<!ELEMENT p_heal_effect (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST p_heal_effect
				value CDATA #REQUIRED
				type CDATA #REQUIRED>

			<!ELEMENT p_elemental_exp_rate (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST p_elemental_exp_rate
				element CDATA #REQUIRED
				value CDATA #REQUIRED>

			<!ELEMENT p_elemental_attack (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST p_elemental_attack
				element CDATA #REQUIRED
				value CDATA #REQUIRED
				type CDATA #REQUIRED>

			<!ELEMENT p_elemental_defence (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST p_elemental_defence
				element CDATA #REQUIRED
				value CDATA #REQUIRED
				type CDATA #REQUIRED>

			<!ELEMENT p_elemental_crit_rate (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST p_elemental_crit_rate
				element CDATA #REQUIRED
				value CDATA #REQUIRED
				type CDATA #REQUIRED>

			<!ELEMENT p_elemental_crit_attack (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST p_elemental_crit_attack
				element CDATA #REQUIRED
				value CDATA #REQUIRED
				type CDATA #REQUIRED>

			<!ELEMENT p_attack_trait (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST p_attack_trait
				name CDATA #REQUIRED
				value CDATA #REQUIRED
				type CDATA #IMPLIED>

			<!ELEMENT p_defence_trait (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST p_defence_trait
				name CDATA #REQUIRED
				value CDATA #REQUIRED
				type CDATA #IMPLIED>

			<!ELEMENT p_vampiric_attack (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST p_vampiric_attack
				value CDATA #REQUIRED
				chance CDATA #IMPLIED>

			<!ELEMENT p_mp_vampiric_attack (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST p_mp_vampiric_attack
				value CDATA #REQUIRED
				chance CDATA #IMPLIED>

			<!ELEMENT mul (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST mul
				order CDATA #IMPLIED
				stat CDATA #REQUIRED
				value CDATA #REQUIRED>

			<!ELEMENT div (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST div
				order CDATA #IMPLIED
				stat CDATA #REQUIRED
				value CDATA #REQUIRED>

			<!ELEMENT sub (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST sub
				order CDATA #IMPLIED
				stat CDATA #REQUIRED
				value CDATA #REQUIRED>

		<!ELEMENT cond (player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST cond
			msgId CDATA #IMPLIED
			addName CDATA #IMPLIED>

			<!ELEMENT or (player|target|using|zone|has|game|or|not|and)*>

			<!ELEMENT not (player|target|using|zone|has|game|or|not|and)*>

			<!ELEMENT and (player|target|using|zone|has|game|or|not|and)*>

			<!ELEMENT player (#PCDATA)>
			<!ATTLIST player
				residence CDATA #IMPLIED
				olympiad CDATA #IMPLIED
				race CDATA #IMPLIED
				instance_zone CDATA #IMPLIED
				is_clan_leader CDATA #IMPLIED
				is_hero CDATA #IMPLIED
				sex CDATA #IMPLIED
				classId CDATA #IMPLIED
				level CDATA #IMPLIED
				minLevel CDATA #IMPLIED
				max_level CDATA #IMPLIED
				min_pDef CDATA #IMPLIED
				max_pDef CDATA #IMPLIED
				avail_max_sp CDATA #IMPLIED
				quest_state CDATA #IMPLIED
				min_pledge_rank CDATA #IMPLIED
				class_type CDATA #IMPLIED
				summon_siege_golem CDATA #IMPLIED
				running CDATA #IMPLIED
				percentHP CDATA #IMPLIED
				resting CDATA #IMPLIED
				min_hp CDATA #IMPLIED
				max_hp CDATA #IMPLIED
				min_mp CDATA #IMPLIED
				max_mp CDATA #IMPLIED
				min_cp CDATA #IMPLIED
				max_cp CDATA #IMPLIED
				min_str CDATA #IMPLIED
				max_str CDATA #IMPLIED
				min_dex CDATA #IMPLIED
				max_dex CDATA #IMPLIED
				min_con CDATA #IMPLIED
				max_con CDATA #IMPLIED
				min_int CDATA #IMPLIED
				max_int CDATA #IMPLIED
				min_wit CDATA #IMPLIED
				max_wit CDATA #IMPLIED
				min_men CDATA #IMPLIED
				max_men CDATA #IMPLIED
				maxPK CDATA #IMPLIED
				percentMP CDATA #IMPLIED
				moving CDATA #IMPLIED
				standing CDATA #IMPLIED
				damage CDATA #IMPLIED
				percentCP CDATA #IMPLIED
				direction CDATA #IMPLIED
				riding CDATA #IMPLIED
				flying CDATA #IMPLIED
				castle_type CDATA #IMPLIED
				min_clan_level CDATA #IMPLIED
				has_abnormal_type CDATA #IMPLIED
				has_summon_id CDATA #IMPLIED
				can_transform CDATA #IMPLIED
				can_untransform CDATA #IMPLIED
				agathion CDATA #IMPLIED
				hasBuffId CDATA #IMPLIED
                hasMaxMpBetween CDATA #IMPLIED
                hasMaxHpBetween CDATA #IMPLIED
                hasHpPercentageBetween CDATA #IMPLIED
                hasMpPercentageBetween CDATA #IMPLIED
                hasCpPercentageBetween CDATA #IMPLIED
                hasMaxCpBetween CDATA #IMPLIED
                hasMaxDpBetween CDATA #IMPLIED
                hasCurrDpBetween CDATA #IMPLIED
				flyingTransform CDATA #IMPLIED
				isFlagged CDATA #IMPLIED
				can_learn_skill CDATA #IMPLIED
				is_chaotic CDATA #IMPLIED
				has_vitality CDATA #IMPLIED
				can_get_costume CDATA #IMPLIED
				can_get_costume_grade CDATA #IMPLIED
				min_light_souls CDATA #IMPLIED
				min_dark_souls CDATA #IMPLIED>

			<!ELEMENT target (#PCDATA)>
			<!ATTLIST target
				is_pet_feed CDATA #IMPLIED
				type CDATA #IMPLIED
				race CDATA #IMPLIED
				hasForbiddenSkill CDATA #IMPLIED
				mobId CDATA #IMPLIED
				npc_class CDATA #IMPLIED
				castledoor CDATA #IMPLIED
				direction CDATA #IMPLIED
				percentHP CDATA #IMPLIED
				has_abnormal_type CDATA #IMPLIED
				forbiddenClassIds CDATA #IMPLIED
				min_distance CDATA #IMPLIED
				max_distance CDATA #IMPLIED
				hasBuffId CDATA #IMPLIED
				playerRace CDATA #IMPLIED
				inhold CDATA #IMPLIED>

			<!ELEMENT using (#PCDATA)>
			<!ATTLIST using
				slotitem CDATA #IMPLIED
				kind CDATA #IMPLIED
				armor CDATA #IMPLIED
				weapon CDATA #IMPLIED
				skill CDATA #IMPLIED>

			<!ELEMENT zone (#PCDATA)>
			<!ATTLIST zone
				type CDATA #IMPLIED
				name CDATA #IMPLIED>

			<!ELEMENT game (#PCDATA)>
			<!ATTLIST game
				night CDATA #IMPLIED>

			<!ELEMENT has (#PCDATA)>
			<!ATTLIST has
				skill CDATA #IMPLIED
				dp CDATA #IMPLIED
                hasMaxMpBetween CDATA #IMPLIED
                hasMaxHpBetween CDATA #IMPLIED
                hasMaxCpBetween CDATA #IMPLIED
                hasMaxDpBetween CDATA #IMPLIED
                hasHpPercentageBetween CDATA #IMPLIED
                hasMpPercentageBetween CDATA #IMPLIED
                hasCpPercentageBetween CDATA #IMPLIED
                hasCurrDpBetween CDATA #IMPLIED
                chance CDATA #IMPLIED>

		<!ELEMENT triggers (trigger)*>
		<!ELEMENT trigger (cond|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST trigger
			id CDATA #IMPLIED
			level CDATA #IMPLIED
			type CDATA #IMPLIED
			chance CDATA #IMPLIED
			cancel_effects_on_remove CDATA #IMPLIED
			increasing CDATA #IMPLIED
			delay CDATA #IMPLIED
			args CDATA #IMPLIED>

		<!ELEMENT enchant (table)*>
		<!ATTLIST enchant
			type CDATA #REQUIRED
			levels CDATA #IMPLIED
			group CDATA #IMPLIED
			name CDATA #IMPLIED>

		<!ELEMENT restoration (group)*>
		<!ATTLIST restoration
			level CDATA #REQUIRED
			consume_item_id CDATA #IMPLIED
			consume_item_count CDATA #IMPLIED
			on_fail_message CDATA #IMPLIED>

			<!ELEMENT group (item)*>
			<!ATTLIST group
				chance CDATA #REQUIRED>

				<!ELEMENT item (#PCDATA)>
				<!ATTLIST item
					id CDATA #REQUIRED
					min_count CDATA #REQUIRED
					max_count CDATA #IMPLIED
					enchant_level CDATA #IMPLIED>

=== rootmp/multiprof/dist/gameserver/data/parser/skills/14700-14799.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skill.dtd">
<list>
	<skill id="14765" levels="5" name="Blood Siphon Resistance">
		<set name="icon" value="icon.skillraid"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="14767" levels="1" name="Siege Punch">
		<set name="affect_scope" value="POINT_BLANK"/>
		<set name="target_type" value="SELF"/>
		<set name="effectPoint" value="-100"/>
		<set name="icon" value="icon.skill0000"/>
		<set name="reuseDelay" value="5000"/>
		<set name="hitTime" value="4600"/>
		<set name="magicLevel" value="85"/>
		<set name="affect_range" value="600"/>
		<set name="target" value="TARGET_AURA"/>
		<set name="skillType" value="PDAM"/>
		<set name="operate_type" value="A1"/>
		<set name="power" value="31500"/>
	</skill>
</list>

=== rootmp/multiprof/dist/gameserver/data/parser/skills/55900-55999.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skill.dtd">
<list>
	<skill id="55901" levels="2" name="Cooking Ingredient">
		<table name="#affect_scope">SINGLE RANGE</table>
		<table name="#icon">icon.skill11775 icon.skill0000</table>
		<table name="#hitTime">1500 1000</table>
		<set name="affect_scope" value="#affect_scope"/>
		<set name="effectPoint" value="-1"/>
		<set name="icon" value="#icon"/>
		<set name="reuseDelay" value="3000"/>
		<set name="coolTime" value="500"/>
		<set name="castRange" value="100"/>
		<set name="hitTime" value="#hitTime"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="A2"/>
	</skill>
</list>

=== rootmp/multiprof/dist/gameserver/data/parser/skills/02500-02599.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skill.dtd">
<list>
	<skill id="2531" levels="1" name="Newbie's Scroll of Escape">
		<set name="icon" value="icon.skill0000"/>
		<set name="hitTime" value="8000"/>
		<set name="ride_state" value="NONE;STRIDER;WYVERN;WOLF"/>
		<set name="magicLevel" value="1"/>
		<set name="magicType" value="SPECIAL"/>
		<set name="itemConsumeId" value="10650"/>
		<set name="itemConsumeCount" value="1"/>
		<set name="hitCancelTime" value="500"/>
		<set name="isHandler" value="true"/>
		<set name="target_type" value="SELF"/>
		<set name="affect_scope" value="SINGLE"/>
		<set name="affect_object" value="FRIEND"/>
		<set name="target" value="TARGET_SELF"/>
		<set name="skillType" value="RECALL"/>
		<set name="operate_type" value="A2"/>
	</skill>
	<skill id="2584" levels="1" name="Item - Special Sound Crystal">
		<set name="icon" value="icon.skill0000"/>
		<set name="ride_state" value="NONE;STRIDER;WYVERN;WOLF"/>
		<set name="magicLevel" value="1"/>
		<set name="magicType" value="SPECIAL"/>
		<set name="target_type" value="SELF"/>
		<set name="affect_scope" value="SINGLE"/>
		<set name="affect_object" value="FRIEND"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTDONE"/>
		<set name="operate_type" value="A2"/>
	</skill>
	<skill id="2585" levels="1" name="Item - Special Sound Crystal">
		<set name="icon" value="icon.skill0000"/>
		<set name="ride_state" value="NONE;STRIDER;WYVERN;WOLF"/>
		<set name="magicLevel" value="1"/>
		<set name="magicType" value="SPECIAL"/>
		<set name="target_type" value="SELF"/>
		<set name="affect_scope" value="SINGLE"/>
		<set name="affect_object" value="FRIEND"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTDONE"/>
		<set name="operate_type" value="A2"/>
	</skill>
	<skill id="2587" levels="1" name="Additional My Teleport slots">
		<set name="icon" value="icon.skill0000"/>
		<set name="target_type" value="SELF"/>
		<set name="affect_scope" value="SINGLE"/>
		<set name="affect_object" value="FRIEND"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="A2"/>
	</skill>
	<skill id="2588" levels="1" name="My Teleport">
		<set name="hitTime" value="2000"/>
		<set name="operate_type" value="A2"/>
		<set name="icon" value="icon.skill0000"/>
		<set name="ride_state" value="NONE;STRIDER;WYVERN;WOLF"/>
		<set name="magicLevel" value="1"/>
		<set name="magicType" value="SPECIAL"/>
		<set name="hitCancelTime" value="500"/>
		<set name="target_type" value="SELF"/>
		<set name="affect_scope" value="SINGLE"/>
		<set name="affect_object" value="FRIEND"/>
		<set name="target" value="TARGET_SELF" />
		<set name="skillType" value="RECALL" />
		<set name="to_flag" value="true"/>
		<set name="operate_type" value="A2" />
		<set name="isSkillTimePermanent" value="true"/>
		<set name="isReuseDelayPermanent" value="true"/>
	</skill>
</list>

=== rootmp/multiprof/dist/gameserver/data/parser/skills/47100-47199.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skill.dtd">
<list>
	<skill id="47101" levels="4" name="Elemental Spirit">
		<!--The spirit power runs through your body.\n\nAn incarnated Spirit Lv. 1 can be used.-->
		<table name="#id">0 47048 47048 47053</table>
		<table name="#level">0 1 1 1</table>
		<set name="icon" value="icon.skill30401"/>
		<set name="operate_type" value="P" />
		<triggers>
			<trigger id="#id" level="#level" type="RECEIVE_DAMAGE" chance="10"/>
		</triggers>
	</skill>
	<skill id="47104" levels="5" name="Elemental Connection">
		<!--The character has a strong connection with the spirits.\n\nSoulshot damage +$s1\nAll Critical Rate +$s2-->
		<set name="icon" value="icon.skill30400"/>
		<table name="#chance">1 1 2 2 3</table>
		<table name="#power">101 102 103 105 110</table>
		<set name="operate_type" value="P"/>
		<for>
			<add stat="mCritRate" value="#chance"/>
			<add stat="pCritRate" value="#chance"/>
			<effect name="i_soul_shot">
				<def name="power" value="#power"/>
			</effect>
		</for>
	</skill>
	<skill id="47105" levels="10" name="Elemental Recovery">
		<!--The spirit power helps to regenerate faster.\n\nHP Recovery Rate +$s1\nMP Recovery Rate +$s2-->
		<set name="icon" value="icon.skill30402"/>
		<table name="#hpRegen">6 7 8 9 10 11 12 13 14 15</table>
		<table name="#mpRegen">3 4 5 6 7 8 8 8 8 8</table>
		<set name="operate_type" value="P"/>
		<for>
			<add stat="regHp" value="#hpRegen"/>
			<add stat="regMp" value="#mpRegen"/>
		</for>
	</skill>
</list>

=== rootmp/multiprof/dist/gameserver/data/parser/skills/18400-18499.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skill.dtd">
<list>
	<skill id="18448" levels="1" name="Scroll: Summon Piero">
		<set name="icon" value="icon.skill0000"/>
		<set name="reuseDelay" value="10000"/>
		<set name="hitTime" value="3000"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="A2"/>
	</skill>
	<skill id="18449" levels="1" name="Magic Number Cube">
		<set name="icon" value="icon.skill0000"/>
		<set name="reuseDelay" value="6000"/>
		<set name="castRange" value="1500"/>
		<set name="hitTime" value="1500"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="A2"/>
	</skill>
	<skill id="18450" levels="6" name="Confirm Number">
		<set name="effectPoint" value="204"/>
		<set name="icon" value="icon.skill0000"/>
		<set name="castRange" value="900"/>
		<set name="hitTime" value="3000"/>
		<set name="mp_consume" value="75"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="A2"/>
	</skill>
	<skill id="18451" levels="2" name="Anniversary Effect">
		<table name="#castRange">900 -1</table>
		<set name="effectPoint" value="1"/>
		<set name="icon" value="icon.ev_buff_11th"/>
		<set name="castRange" value="#castRange"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="A2"/>
	</skill>
	<skill id="18472" levels="6" name="Giveaway Number 1">
		<set name="icon" value="icon.skill0000"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="A2"/>
	</skill>
	<skill id="18475" levels="1" name="Anniversary Coin">
		<set name="effectPoint" value="1"/>
		<set name="icon" value="icon.ev_buff_11th"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="A2"/>
	</skill>
</list>

=== rootmp/multiprof/dist/gameserver/data/parser/skills/11300-11399.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skill.dtd">
<list>
	<skill id="11316" levels="1" name="Summon Soulshots">
		<set name="icon" value="icon.skill11316"/>
		<set name="reuseDelay" value="3000"/>
		<set name="hitTime" value="1000"/>
		<set name="mp_consume" value="10"/>
		<set name="autouse_type" value="ATTACK"/>
		<set name="magicLevel" value="40"/>
		<set name="magicType" value="MAGIC"/>
		<set name="target" value="TARGET_SELF"/>
		<set name="skillType" value="RESTORATION"/>
		<set name="operate_type" value="A1"/>
		<set name="itemConsumeId" value="1785"/>
		<set name="itemConsumeCount" value="4"/>
		<restoration level="1">
			<group chance="100.0">
				<item id="6645" min_count="30" max_count="30"/>	<!--Заряд Души Зверя-->
			</group>
		</restoration>
	</skill>
	<skill id="11317" levels="1" name="Mass Summon Soulshots">
		<set name="icon" value="BranchIcon.Icon.g_bm_antaras_pocket_i00"/>
		<set name="reuseDelay" value="3000"/>
		<set name="hitTime" value="1000"/>
		<set name="mp_consume" value="50"/>
		<set name="autouse_type" value="ATTACK"/>
		<set name="magicType" value="MAGIC"/>
		<set name="target" value="TARGET_SELF"/>
		<set name="skillType" value="RESTORATION"/>
		<set name="operate_type" value="A1"/>
		<set name="itemConsumeId" value="1785"/>
		<set name="itemConsumeCount" value="40"/>
		<restoration level="1">
			<group chance="100.0">
				<item id="6645" min_count="300" max_count="300"/>	<!--Заряд Души Зверя-->
			</group>
		</restoration>
	</skill>
	<skill id="11318" levels="1" name="Summon Spiritshots">
		<set name="icon" value="icon.skill11316"/>
		<set name="reuseDelay" value="3000"/>
		<set name="hitTime" value="1000"/>
		<set name="mp_consume" value="10"/>
		<set name="autouse_type" value="ATTACK"/>
		<set name="magicLevel" value="40"/>
		<set name="magicType" value="MAGIC"/>
		<set name="target" value="TARGET_SELF"/>
		<set name="skillType" value="RESTORATION"/>
		<set name="operate_type" value="A1"/>
		<set name="itemConsumeId" value="3031"/>
		<set name="itemConsumeCount" value="4"/>
		<restoration level="1">
			<group chance="100.0">
				<item id="6646" min_count="24" max_count="24"/>	<!--Заряд Духа Зверя-->
			</group>
		</restoration>
	</skill>
	<skill id="11319" levels="1" name="Mass Summon Spiritshots">
		<set name="icon" value="BranchIcon.Icon.g_bm_antaras_pocket_i00"/>
		<set name="reuseDelay" value="3000"/>
		<set name="hitTime" value="1000"/>
		<set name="mp_consume" value="50"/>
		<set name="autouse_type" value="ATTACK"/>
		<set name="magicType" value="MAGIC"/>
		<set name="target" value="TARGET_SELF"/>
		<set name="skillType" value="RESTORATION"/>
		<set name="operate_type" value="A1"/>
		<set name="itemConsumeId" value="3031"/>
		<set name="itemConsumeCount" value="40"/>
		<restoration level="1">
			<group chance="100.0">
				<item id="6646" min_count="240" max_count="240"/>	<!--Заряд Духа Зверя-->
			</group>
		</restoration>
	</skill>
</list>
