=== rootmp/multiprof/dist/gameserver/data/parser/buylists/buylist.dtd
<!ELEMENT list (npc)*>

	<!ELEMENT npc (buylist)*>
	<!ATTLIST npc
		id CDATA #REQUIRED>

		<!ELEMENT buylist (item)*>
		<!ATTLIST buylist
			id CDATA #REQUIRED
			base_markup CDATA #IMPLIED>

			<!ELEMENT item (#PCDATA)>
			<!ATTLIST item
				id CDATA #REQUIRED
				markup CDATA #IMPLIED
				price CDATA #IMPLIED
				count CDATA #IMPLIED
				time CDATA #IMPLIED>

=== rootmp/multiprof/dist/gameserver/data/parser/buylists/npc/30518.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "buylist.dtd">
<!--AUTHOR: Bonux-->
<list>
	<npc id="30518">	<!--Ювелир Гарита-->
		<buylist id="1" base_markup="20">
			<item id="118"/>	<!--Magic Necklace-->
			<item id="112"/>	<!--Apprentice's Earring-->
			<item id="116"/>	<!--Magic Ring-->
			<item id="906"/>	<!--Necklace of Knowledge-->
			<item id="113"/>	<!--Mage Earring-->
			<item id="875"/>	<!--Ring of Knowledge-->
			<item id="907"/>	<!--Necklace of Anguish-->
			<item id="114"/>	<!--Earring of Strength-->
			<item id="115"/>	<!--Earring of Wisdom-->
			<item id="876"/>	<!--Ring of Anguish-->
			<item id="908"/>	<!--Necklace of Wisdom-->
			<item id="845"/>	<!--Cat's Eye-->
			<item id="877"/>	<!--Ring of Wisdom-->
		</buylist>
	</npc>
</list>
