=== rootmp/multiprof/dist/gameserver/data/parser/player_parameters/class_data/class_data.dtd
<!ELEMENT list (class_data)*>
<!ELEMENT class_data (hp_mp_cp_data)*>
<!ATTLIST class_data
	class_id CDATA #REQUIRED>

<!ELEMENT hp_mp_cp_data (hp_mp_cp)*>
<!ELEMENT hp_mp_cp (#PCDATA)>
<!ATTLIST hp_mp_cp
	lvl CDATA #REQUIRED
	hp CDATA #REQUIRED
	mp CDATA #REQUIRED
	cp CDATA #REQUIRED>

=== rootmp/multiprof/dist/gameserver/data/parser/player_parameters/class_data/[0] fighter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "class_data.dtd">
<!--AUTHOR: Bonux-->
<list>
	<class_data class_id="0">
		<hp_mp_cp_data>
			<hp_mp_cp lvl="1" hp="80.0" mp="30.0" cp="32.0"/>
			<hp_mp_cp lvl="2" hp="91.83" mp="35.46" cp="36.732"/>
			<hp_mp_cp lvl="3" hp="103.79" mp="40.98" cp="41.516"/>
			<hp_mp_cp lvl="4" hp="115.88" mp="46.56" cp="46.352"/>
			<hp_mp_cp lvl="5" hp="128.1" mp="52.2" cp="51.24"/>
			<hp_mp_cp lvl="6" hp="140.45" mp="57.9" cp="56.18"/>
			<hp_mp_cp lvl="7" hp="152.93" mp="63.66" cp="61.172"/>
			<hp_mp_cp lvl="8" hp="165.54" mp="69.48" cp="66.216"/>
			<hp_mp_cp lvl="9" hp="178.28" mp="75.36" cp="71.312"/>
			<hp_mp_cp lvl="10" hp="191.15" mp="81.3" cp="76.46"/>
			<hp_mp_cp lvl="11" hp="204.15" mp="87.3" cp="81.66"/>
			<hp_mp_cp lvl="12" hp="217.28" mp="93.36" cp="86.912"/>
			<hp_mp_cp lvl="13" hp="230.54" mp="99.48" cp="92.216"/>
			<hp_mp_cp lvl="14" hp="243.93" mp="105.66" cp="97.572"/>
			<hp_mp_cp lvl="15" hp="257.45" mp="111.9" cp="102.98"/>
			<hp_mp_cp lvl="16" hp="271.1" mp="118.2" cp="108.44"/>
			<hp_mp_cp lvl="17" hp="284.88" mp="124.56" cp="113.952"/>
			<hp_mp_cp lvl="18" hp="298.79" mp="130.98" cp="119.516"/>
			<hp_mp_cp lvl="19" hp="312.83" mp="137.46" cp="125.132"/>
			<hp_mp_cp lvl="20" hp="327.0" mp="144.0" cp="130.8"/>
			<hp_mp_cp lvl="21" hp="341.3" mp="150.6" cp="136.52"/>
			<hp_mp_cp lvl="22" hp="355.73" mp="157.26" cp="142.292"/>
			<hp_mp_cp lvl="23" hp="370.29" mp="163.98" cp="148.116"/>
			<hp_mp_cp lvl="24" hp="384.98" mp="170.76" cp="153.992"/>
			<hp_mp_cp lvl="25" hp="399.8" mp="177.6" cp="159.92"/>
			<hp_mp_cp lvl="26" hp="414.75" mp="184.5" cp="165.9"/>
			<hp_mp_cp lvl="27" hp="429.83" mp="191.46" cp="171.932"/>
			<hp_mp_cp lvl="28" hp="445.04" mp="198.48" cp="178.016"/>
			<hp_mp_cp lvl="29" hp="460.38" mp="205.56" cp="184.152"/>
			<hp_mp_cp lvl="30" hp="475.85" mp="212.7" cp="190.34"/>
			<hp_mp_cp lvl="31" hp="491.45" mp="219.9" cp="196.58"/>
			<hp_mp_cp lvl="32" hp="507.18" mp="227.16" cp="202.872"/>
			<hp_mp_cp lvl="33" hp="523.04" mp="234.48" cp="209.216"/>
			<hp_mp_cp lvl="34" hp="539.03" mp="241.86" cp="215.612"/>
			<hp_mp_cp lvl="35" hp="555.15" mp="249.3" cp="222.06"/>
			<hp_mp_cp lvl="36" hp="571.4" mp="256.8" cp="228.56"/>
			<hp_mp_cp lvl="37" hp="587.78" mp="264.36" cp="235.112"/>
			<hp_mp_cp lvl="38" hp="604.29" mp="271.98" cp="241.716"/>
			<hp_mp_cp lvl="39" hp="620.93" mp="279.66" cp="248.372"/>
			<hp_mp_cp lvl="40" hp="637.7" mp="287.4" cp="255.08"/>
			<hp_mp_cp lvl="41" hp="654.6" mp="295.2" cp="261.84"/>
			<hp_mp_cp lvl="42" hp="671.63" mp="303.06" cp="268.652"/>
			<hp_mp_cp lvl="43" hp="688.79" mp="310.98" cp="275.516"/>
			<hp_mp_cp lvl="44" hp="706.08" mp="318.96" cp="282.432"/>
			<hp_mp_cp lvl="45" hp="723.5" mp="327.0" cp="289.4"/>
			<hp_mp_cp lvl="46" hp="741.05" mp="335.1" cp="296.42"/>
			<hp_mp_cp lvl="47" hp="758.73" mp="343.26" cp="303.492"/>
			<hp_mp_cp lvl="48" hp="776.54" mp="351.48" cp="310.616"/>
			<hp_mp_cp lvl="49" hp="794.48" mp="359.76" cp="317.792"/>
			<hp_mp_cp lvl="50" hp="812.55" mp="368.1" cp="325.02"/>
			<hp_mp_cp lvl="51" hp="830.75" mp="376.5" cp="332.3"/>
			<hp_mp_cp lvl="52" hp="849.08" mp="384.96" cp="339.632"/>
			<hp_mp_cp lvl="53" hp="867.54" mp="393.48" cp="347.016"/>
			<hp_mp_cp lvl="54" hp="886.13" mp="402.06" cp="354.452"/>
			<hp_mp_cp lvl="55" hp="904.85" mp="410.7" cp="361.94"/>
			<hp_mp_cp lvl="56" hp="923.7" mp="419.4" cp="369.48"/>
			<hp_mp_cp lvl="57" hp="942.68" mp="428.16" cp="377.072"/>
			<hp_mp_cp lvl="58" hp="961.79" mp="436.98" cp="384.716"/>
			<hp_mp_cp lvl="59" hp="981.03" mp="445.86" cp="392.412"/>
			<hp_mp_cp lvl="60" hp="1000.4" mp="454.8" cp="400.16"/>
			<hp_mp_cp lvl="61" hp="1019.9" mp="463.8" cp="407.96"/>
			<hp_mp_cp lvl="62" hp="1039.53" mp="472.86" cp="415.812"/>
			<hp_mp_cp lvl="63" hp="1059.29" mp="481.98" cp="423.716"/>
			<hp_mp_cp lvl="64" hp="1079.18" mp="491.16" cp="431.672"/>
			<hp_mp_cp lvl="65" hp="1099.2" mp="500.4" cp="439.68"/>
			<hp_mp_cp lvl="66" hp="1119.35" mp="509.7" cp="447.74"/>
			<hp_mp_cp lvl="67" hp="1139.63" mp="519.06" cp="455.852"/>
			<hp_mp_cp lvl="68" hp="1160.04" mp="528.48" cp="464.016"/>
			<hp_mp_cp lvl="69" hp="1180.58" mp="537.96" cp="472.232"/>
			<hp_mp_cp lvl="70" hp="1201.25" mp="547.5" cp="480.5"/>
			<hp_mp_cp lvl="71" hp="1222.05" mp="557.1" cp="488.82"/>
			<hp_mp_cp lvl="72" hp="1242.98" mp="566.76" cp="497.192"/>
			<hp_mp_cp lvl="73" hp="1264.04" mp="576.48" cp="505.616"/>
			<hp_mp_cp lvl="74" hp="1285.23" mp="586.26" cp="514.092"/>
			<hp_mp_cp lvl="75" hp="1306.55" mp="596.1" cp="522.62"/>
			<hp_mp_cp lvl="76" hp="1328.0" mp="606.0" cp="531.2"/>
			<hp_mp_cp lvl="77" hp="1349.58" mp="615.96" cp="539.832"/>
			<hp_mp_cp lvl="78" hp="1371.29" mp="625.98" cp="548.516"/>
			<hp_mp_cp lvl="79" hp="1393.13" mp="636.06" cp="557.252"/>
			<hp_mp_cp lvl="80" hp="1415.1" mp="646.2" cp="566.04"/>
			<hp_mp_cp lvl="81" hp="1437.2" mp="656.4" cp="574.88"/>
			<hp_mp_cp lvl="82" hp="1459.43" mp="666.66" cp="583.772"/>
			<hp_mp_cp lvl="83" hp="1481.79" mp="676.98" cp="592.716"/>
			<hp_mp_cp lvl="84" hp="1504.28" mp="687.36" cp="601.712"/>
			<hp_mp_cp lvl="85" hp="1526.9" mp="697.8" cp="610.76"/>
			<hp_mp_cp lvl="86" hp="1549.65" mp="708.3" cp="619.86"/>
			<hp_mp_cp lvl="87" hp="1572.53" mp="718.86" cp="629.012"/>
			<hp_mp_cp lvl="88" hp="1595.54" mp="729.48" cp="638.216"/>
			<hp_mp_cp lvl="89" hp="1618.68" mp="740.16" cp="647.472"/>
			<hp_mp_cp lvl="90" hp="1641.95" mp="750.9" cp="656.78"/>
			<hp_mp_cp lvl="91" hp="1665.35" mp="761.7" cp="666.14"/>
			<hp_mp_cp lvl="92" hp="1688.88" mp="772.56" cp="675.552"/>
			<hp_mp_cp lvl="93" hp="1712.54" mp="783.48" cp="685.016"/>
			<hp_mp_cp lvl="94" hp="1736.33" mp="794.46" cp="694.532"/>
			<hp_mp_cp lvl="95" hp="1760.25" mp="805.5" cp="704.1"/>
			<hp_mp_cp lvl="96" hp="1784.3" mp="816.6" cp="713.72"/>
			<hp_mp_cp lvl="97" hp="1808.48" mp="827.76" cp="723.392"/>
			<hp_mp_cp lvl="98" hp="1832.79" mp="838.98" cp="733.116"/>
			<hp_mp_cp lvl="99" hp="1857.23" mp="850.26" cp="742.892"/>
		</hp_mp_cp_data>
	</class_data>
</list>
