=== rootmp/multiprof/dist/gameserver/data/parser/multisell/multisell.dtd
<!ELEMENT list (config|item)*>
<!ELEMENT config (#PCDATA)>
<!ATTLIST config
	show_all CDATA #IMPLIED
	no_tax CDATA #IMPLIED
	no_key CDATA #IMPLIED
	keep_enchanted CDATA #IMPLIED
	type CDATA #IMPLIED>
<!ELEMENT item (ingredient|production)*>
<!ELEMENT ingredient (#PCDATA)>
<!ATTLIST ingredient
	count CDATA #REQUIRED
	id CDATA #REQUIRED>
<!ELEMENT production (#PCDATA)>
<!ATTLIST production
	count CDATA #REQUIRED
	id CDATA #REQUIRED
	chance CDATA #IMPLIED
	flags CDATA #IMPLIED
	durablity CDATA #IMPLIED
	temporal CDATA #IMPLIED
	enchant CDATA #IMPLIED>

=== rootmp/multiprof/dist/gameserver/data/parser/multisell/4686.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "multisell.dtd">
<!--AUTHOR: Bonux-->
<list>
	<config no_tax="true"/>
	<item>
		<production id="71437" count="1"/>	<!--Shining Jewel Box-->
		<ingredient id="71438" count="1"/>	<!--Jewel Coin-->
		<ingredient id="57" count="2000000"/>	<!--Adena-->
	</item>
	<item>
		<production id="90311" count="1"/>	<!--Brooch Lv. 1-->
		<ingredient id="71438" count="1"/>	<!--Jewel Coin-->
	</item>
	<item>
		<production id="90312" count="1"/>	<!--Brooch Lv. 2-->
		<ingredient id="71438" count="50"/>	<!--Jewel Coin-->
		<ingredient id="90311" count="1"/>	<!--Brooch Lv. 1-->
		<ingredient id="57" count="30000000"/>	<!--Adena-->
	</item>
</list>

=== rootmp/multiprof/dist/gameserver/data/parser/multisell/404.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "multisell.dtd">
<!--AUTHOR: Bonux-->
<list>
	<item>
		<production id="45493" count="1"/>	<!--Fishing Rod Pack (1-day)-->
		<ingredient id="57" count="20514"/>	<!--Adena-->
	</item>
	<item>
		<production id="38154" count="1"/>	<!--Fishing Shot-->
		<ingredient id="57" count="28"/>	<!--Adena-->
	</item>
	<item>
		<production id="45495" count="1"/>	<!--Normal Bait-->
		<ingredient id="57" count="7"/>	<!--Adena-->
	</item>
</list>

=== rootmp/multiprof/dist/gameserver/data/parser/multisell/4117.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "multisell.dtd">
<list>
	<config type="CHANCED"/>
	<item>
		<production id="70295" count="1"/>	<!--Талисман Границы +2-->
		<production id="70295" count="1" chance="50"/>	<!--Талисман Границы +2-->
		<production id="70294" count="1" chance="50"/>	<!--Талисман Границы +1-->
		<ingredient id="70294" count="1"/>	<!--Талисман Границы +1-->
		<ingredient id="70294" count="1"/>	<!--Талисман Границы +1-->
	</item>
	<item>
		<production id="70296" count="1"/>	<!--Талисман Границы +3-->
		<production id="70296" count="1" chance="40"/>	<!--Талисман Границы +3-->
		<production id="70295" count="1" chance="60"/>	<!--Талисман Границы +2-->
		<ingredient id="70295" count="1"/>	<!--Талисман Границы +2-->
		<ingredient id="70295" count="1"/>	<!--Талисман Границы +2-->
	</item>
	<item>
		<production id="70297" count="1"/>	<!--Талисман Границы +4-->
		<production id="70297" count="1" chance="20"/>	<!--Талисман Границы +4-->
		<production id="70296" count="1" chance="80"/>	<!--Талисман Границы +3-->
		<ingredient id="70296" count="1"/>	<!--Талисман Границы +3-->
		<ingredient id="70296" count="1"/>	<!--Талисман Границы +3-->
	</item>
	<item>
		<production id="70298" count="1"/>	<!--Талисман Границы +5-->
		<production id="70298" count="1" chance="10"/>	<!--Талисман Границы +5-->
		<production id="70297" count="1" chance="90"/>	<!--Талисман Границы +4-->
		<ingredient id="70297" count="1"/>	<!--Талисман Границы +4-->
		<ingredient id="70297" count="1"/>	<!--Талисман Границы +4-->
	</item>
</list>
